#!/usr/bin/env python3
"""
s4_fullstack.py — S4 session 1: the unified model (all sectors, one system)
(Shape Zero action log item S4 — "the honest version of testing the entire model")

UNIFICATION THESIS: each lattice site is a cone point z_n in R^2 (development
coords). mass m_n = |z_n|^2; angular motion = the wave sector. Elastic
coupling (c/2)|z_{n+1}-z_n|^2 IS the local HK transport cost. On-site
potential = void + alignment: V_n = g/|z_n|^2 + delta*|z_n - w|^2.
Gyroscopic velocity coupling c*beta*(zdot_{n+1}-zdot_{n-1}) componentwise
(telescoping => conservative on the ring). Nonlinearity is NOT pasted in:
it is generated by the void term's anharmonicity.

PREDICTIONS STATED BEFORE RUNNING (g=0.1, delta=1, |w|=1, c=1, beta=0.05,
N=48, k=pi/2):
 P1 equilibrium: all z = (r_eq, 0) with r_eq solving 2*delta*(r-1)=2g/r^3
    (Newton below; approx 1.0803), m_eq = r_eq^2 above the floor 0.3162.
 P2 branch split, ANALYTIC: site Hessian is diag(2d+6g/r^4, 2d-2g/r^4):
    the void STIFFENS the radial (mass) branch and SOFTENS the angular
    (wave) branch — a coexistence deformation invisible to either old
    sector. omega_theta(k)^2 = 2d - 2g/r^4 + 4c sin^2(k/2),
    omega_r(k)^2     = 2d + 6g/r^4 + 4c sin^2(k/2).
 P3 U(1) carryover, stiffness-free and branch-blind: the gyroscopic
    asymmetry |omega(+k)-omega(-k)| = 2*c*beta*sin(k) = 0.1000 at k=pi/2
    on BOTH branches (leading order, independent of on-site stiffness).
 P4 conservativity: total energy (kinetic flat in z + all potentials)
    conserved to integrator precision with gyro ON.
 P5 floor under transport: min_n m_n stays above sqrt(g/delta)=0.3162
    during a strong angular wave (a=0.30); expected to stay near m_eq.
"""

import numpy as np

G, DELTA, C, BETA = 0.1, 1.0, 1.0, 0.05
N, DT = 48, 0.01
W = np.array([1.0, 0.0])

def r_equilibrium():
    r = 1.0
    for _ in range(60):
        f = -2*G/r**3 + 2*DELTA*(r - 1.0)
        df = 6*G/r**4 + 2*DELTA
        r -= f/df
    return r

REQ = r_equilibrium()

def forces(Z, V):
    # on-site: void + alignment
    r2 = np.sum(Z*Z, axis=1, keepdims=True)
    F = 2*G/(r2*r2) * Z - 2*DELTA*(Z - W)
    # elastic = local HK transport chord
    F += C * (np.roll(Z, -1, 0) + np.roll(Z, 1, 0) - 2*Z)
    # gyroscopic (componentwise, conservative by telescoping)
    F += C*BETA * (np.roll(V, -1, 0) - np.roll(V, 1, 0))
    return F

def energy(Z, V):
    r2 = np.sum(Z*Z, axis=1)
    E = 0.5*np.sum(V*V) + np.sum(G/r2) + DELTA*np.sum((Z-W)**2)
    d = np.roll(Z, -1, 0) - Z
    return E + 0.5*C*np.sum(d*d)

def run(Z0, V0, T):
    Z, V = Z0.copy(), V0.copy()
    E0 = energy(Z, V); dEmax = 0.0
    traj = []
    for i in range(int(T/DT)):
        # velocity-dependent force: RK4 on (Z,V) jointly
        a1 = forces(Z, V);                         v1 = V
        a2 = forces(Z+DT/2*v1, V+DT/2*a1);         v2 = V+DT/2*a1
        a3 = forces(Z+DT/2*v2, V+DT/2*a2);         v3 = V+DT/2*a2
        a4 = forces(Z+DT*v3,  V+DT*a3);            v4 = V+DT*a3
        Z = Z + DT/6*(v1+2*v2+2*v3+v4)
        V = V + DT/6*(a1+2*a2+2*a3+a4)
        dEmax = max(dEmax, abs(energy(Z, V)-E0))
        if i % 2 == 0: traj.append(Z.copy())
    return Z, V, dEmax/abs(E0), np.array(traj)

def wave_frequency(branch, k_sign, a=0.01, T=60.0):
    """Launch a traveling wave on one branch; measure omega from mode phase."""
    n = np.arange(N); k = 2*np.pi*12/N * k_sign        # |k| = pi/2
    comp = 1 if branch == 'theta' else 0
    w0sq = (2*DELTA + (6 if branch=='r' else -2)*G/REQ**4
            + 4*C*np.sin(abs(k)/2)**2)
    w0 = np.sqrt(w0sq)
    Z0 = np.tile([REQ, 0.0], (N,1)); V0 = np.zeros((N,2))
    Z0[:, comp] += a*np.cos(k*n)
    V0[:, comp] += a*w0*np.sin(k*n)
    _, _, dE, traj = run(Z0, V0, T)
    u = traj[:, :, comp] - (REQ if comp==0 else 0.0)
    Uk = u @ np.exp(-1j*k*n)
    ph = np.unwrap(np.angle(Uk))
    t = np.arange(len(ph)) * 2*DT
    om = -np.polyfit(t, ph, 1)[0]
    return om, w0, dE

if __name__ == '__main__':
    print(f'P1 r_eq = {REQ:.5f}  m_eq = {REQ**2:.5f}  '
          f'floor m = {np.sqrt(G/DELTA):.4f}\n')
    print(f'{"branch":>7} {"k":>4} {"omega_meas":>11} {"omega_pred":>11} {"dE/E":>9}')
    res = {}
    for br in ('theta', 'r'):
        for s in (+1, -1):
            om, w0, dE = wave_frequency(br, s)
            res[(br, s)] = om
            print(f'{br:>7} {"+" if s>0 else "-"}π/2 {om:>11.5f} {w0:>11.5f} {dE:>9.1e}')
    print()
    for br in ('theta', 'r'):
        asym = res[(br, +1)] - res[(br, -1)]
        print(f'P3 {br:>6}-branch asymmetry = {asym:+.5f}   '
              f'predicted magnitude 2cβ sin k = {2*C*BETA:.4f}')
    # P5: strong wave, floor check
    n = np.arange(N); k = 2*np.pi*12/N
    Z0 = np.tile([REQ, 0.0], (N,1)); V0 = np.zeros((N,2))
    w0 = np.sqrt(2*DELTA - 2*G/REQ**4 + 4*C*np.sin(k/2)**2)
    Z0[:,1] += 0.30*np.cos(k*n); V0[:,1] += 0.30*w0*np.sin(k*n)
    _, _, dE, traj = run(Z0, V0, 80.0)
    mmin = np.min(np.sum(traj*traj, axis=2))
    print(f'\nP5 strong wave a=0.30: min mass = {mmin:.4f} '
          f'(floor {np.sqrt(G/DELTA):.4f})   dE/E = {dE:.1e}')
    print('P4 conservativity: see dE/E columns (gyro ON in all runs).')
