#!/usr/bin/env python3
"""
z1_d8_flow.py — an evolution law written without reference to sectors

The defined version of this construction would build sector behaviour in. This
is the honest version: write the law from the program's own principles, say
nothing about Fano lines or associativity, and see whether sector structure
appears on its own. If it does not, the failure informs what a defined version
would have to add.

THE LAW, from the principles alone.
  state        psi in S^7, the unit octonions (chosen over flat O in the
               previous session because the loop is where D8 differs from D4)
  conservativity  the evolution does no net work, so |psi| is preserved and
               psi-dot is orthogonal to psi
  minimality   no free continuous parameter beyond what is forced

The simplest evolution built from the algebra alone is right multiplication by
a fixed imaginary octonion:

        psi-dot = psi * a ,      a in Im(O),  |a| = 1

For imaginary a this is automatically orthogonal to psi, so conservativity is
satisfied without imposing anything. ONE generator. No sectors mentioned.

PLURALITY. The program purchases exactly one assumption: that there is more
than one dynamical degree of freedom. Spending it gives a second generator, and
the minimal conservative two-generator law is

        psi-dot = psi * a  +  b * psi

left and right multiplication together, both norm-preserving for imaginary a, b.

WHAT IS BEING TESTED. Nothing here references Artin, Fano lines, or the term
census. The measurements are basis-independent: the dimension of the subspace
the trajectory sweeps, and whether the associator vanishes on that subspace.
Whether those line up with the sector structure found earlier is the question,
not an input.

PREDICTIONS STATED BEFORE RUNNING
 F1 the one-generator flow conserves |psi| to 1e-12 under integration.
 F2 the one-generator trajectory sweeps a 4-dimensional subspace and the
    associator vanishes on it to machine precision -- i.e. it is confined to a
    quaternion subalgebra WITHOUT that having been imposed.
    [MISSED, and tighter than predicted: the sweep is 2-dimensional. The
    solution psi(t) = psi_0 exp(at) traces psi_0 times the COMPLEX subalgebra
    generated by a, not the quaternion one. Associator 4.9e-16, so confinement
    holds -- but the one-generator flow does not reach D4. It stays at D2.]
 F3 the two-generator flow sweeps MORE than 4 dimensions and the associator on
    its span is nonzero.
 F4 therefore the condition for leaving a sector is exactly PLURALITY: a single
    degree of freedom cannot leave, and the program's one purchased assumption
    is what permits it.
 F5 evaluated on the swept support, the one-generator flow admits the
    sector-local term count and the two-generator flow the full count.

Python 3 + NumPy only.
"""

import numpy as np
import importlib.util
import os
from itertools import permutations

_here = os.path.dirname(os.path.abspath(__file__))
spec = importlib.util.spec_from_file_location(
    "ch", os.path.join(_here, "d8_channels.py"))
ch = importlib.util.module_from_spec(spec)
spec.loader.exec_module(ch)


def oct_table(orient):
    E = np.zeros((8, 8, 8))
    E[0, :, :] = np.eye(8)
    E[:, 0, :] = np.eye(8)
    for i in range(1, 8):
        E[i, i, 0] = -1
    for (a, b, c) in orient:
        for x, y, z in ((a, b, c), (b, c, a), (c, a, b)):
            E[x, y, z] = 1
            E[y, x, z] = -1
    return E


def mul(x, y, E):
    return np.einsum('ijk,i,j->k', E, x, y)


def assoc(x, y, z, E):
    return mul(mul(x, y, E), z, E) - mul(x, mul(y, z, E), E)


def integrate(psi0, rhs, T=40.0, n=8000):
    dt = T / n
    psi = psi0.copy()
    traj = [psi.copy()]
    for _ in range(n):
        k1 = rhs(psi)
        k2 = rhs(psi + 0.5 * dt * k1)
        k3 = rhs(psi + 0.5 * dt * k2)
        k4 = rhs(psi + dt * k3)
        psi = psi + (dt / 6.0) * (k1 + 2 * k2 + 2 * k3 + k4)
        traj.append(psi.copy())
    return np.array(traj)


def span_dim(traj, tol=1e-8):
    sv = np.linalg.svd(traj, compute_uv=False)
    return int(np.sum(sv > tol * sv[0])), sv


def assoc_on_span(traj, E, rng, tol=1e-8, trials=300):
    sv_dim, _ = span_dim(traj, tol)
    U, s, Vt = np.linalg.svd(traj, full_matrices=False)
    basis = Vt[:sv_dim]
    worst = 0.0
    for _ in range(trials):
        x, y, z = (rng.normal(size=sv_dim) @ basis for _ in range(3))
        nrm = np.linalg.norm(x) * np.linalg.norm(y) * np.linalg.norm(z)
        worst = max(worst, np.linalg.norm(assoc(x, y, z, E)) / max(nrm, 1e-30))
    return worst, basis


def main():
    orient = ch.oriented_lines()
    E = oct_table(orient)
    c = ch.imaginary_c(orient)
    I7 = np.eye(7)
    rng = np.random.default_rng(211)
    print("=" * 70)
    print("A D8 FLOW WRITTEN WITHOUT REFERENCE TO SECTORS")
    print("=" * 70)

    # generic, non-basis-aligned initial data
    psi0 = rng.normal(size=8)
    psi0 /= np.linalg.norm(psi0)
    a = np.zeros(8)
    a[1:] = rng.normal(size=7)
    a[1:] /= np.linalg.norm(a[1:])
    b = np.zeros(8)
    b[1:] = rng.normal(size=7)
    b[1:] /= np.linalg.norm(b[1:])

    print("\nF1  CONSERVATIVITY UNDER INTEGRATION")
    print("-" * 70)
    tr1 = integrate(psi0, lambda p: mul(p, a, E))
    tr2 = integrate(psi0, lambda p: mul(p, a, E) + mul(b, p, E))
    for name, tr in (("one generator ", tr1), ("two generators", tr2)):
        drift = np.max(np.abs(np.linalg.norm(tr, axis=1) - 1.0))
        print(f"    {name} : max | |psi| - 1 | = {drift:.3e}"
              f"   [{'PASS' if drift < 1e-10 else 'MISS'}]")

    print("\nF2/F3  WHAT THE TRAJECTORY SWEEPS")
    print("-" * 70)
    print("      law              span dim   associator on the span")
    d1, _ = span_dim(tr1)
    w1, _ = assoc_on_span(tr1, E, rng)
    d2, _ = span_dim(tr2)
    w2, _ = assoc_on_span(tr2, E, rng)
    print(f"    psi' = psi a        {d1:2d}        {w1:.3e}")
    print(f"    psi' = psi a + b psi {d2:2d}        {w2:.3e}")
    print(f"\n    F2 one generator: span 4 and associator zero : "
          f"{'PASS' if d1 == 4 and w1 < 1e-9 else 'MISS'}")
    print(f"    F3 two generators: span > 4, associator > 0   : "
          f"{'PASS' if d2 > 4 and w2 > 1e-6 else 'MISS'}")

    # ---- F5 term count on the swept support -------------------------
    print("\nF5  TERM COUNT ON THE SWEPT SUPPORT")
    print("-" * 70)
    T34, CUR = ch.terms_34(), ch.currents()
    NS = 200

    def counts_on(basis8):
        """Project the imaginary part of the swept span into a 7x7 projector."""
        im = basis8[:, 1:]
        Q = np.linalg.qr(im.T)[0]
        r = np.linalg.matrix_rank(im, tol=1e-8)
        P = Q[:, :r] @ Q[:, :r].T
        J = rng.normal(size=(NS, 7, 7))
        H = rng.normal(size=(NS, 7, 7, 7))
        H = 0.5 * (H + np.transpose(H, (0, 2, 1, 3)))
        J = np.einsum('ij,zjk,kl->zil', P, J, P)
        H = np.einsum('ij,zjkl,km,ln->zimn', P, H, P, P)
        A = np.stack([ch.eval_34(t, J, H, c, I7) for t in T34], axis=1)
        B = np.stack([ch.eval_div(v, J, H, c, I7) for v in CUR], axis=1)
        # ABSOLUTE floor as well as relative. On a 2-dimensional support every
        # invariant vanishes identically, the whole matrix sits at ~1e-14, and
        # a purely relative threshold then admits noise and reported rank 67 --
        # above the full-space value of 22, which is impossible under a
        # restriction. That was the bug.
        def rk(M):
            sv = np.linalg.svd(M, compute_uv=False)
            return int(np.sum((sv > 1e-8 * sv[0]) & (sv > 1e-9)))
        return r, rk(A), rk(B)

    _, b1 = assoc_on_span(tr1, E, rng)
    _, b2 = assoc_on_span(tr2, E, rng)
    for name, bas in (("one generator ", b1), ("two generators", b2)):
        r, ra, rb = counts_on(bas)
        print(f"    {name} : imaginary support dim {r}   "
              f"dim {ra:3d}  div {rb:3d}  non-null {ra - rb:3d}")

    print("\n" + "=" * 70)
    print("READING")
    print("=" * 70)
    if w1 < 1e-9 and d2 > d1 and w2 > 1e-6:
        print("  Confinement is NOT imposed here -- it emerges. A law built")
        print("  from conservativity and minimality alone, with one generator,")
        print("  sweeps a 2-plane -- psi_0 times the complex subalgebra")
        print("  generated by a -- and never leaves it. Nothing in the")
        print("  construction mentions Fano lines or Artin's theorem, and the")
        print("  one-generator flow does not even reach D4.")
        print()
        print("  And what permits leaving is PLURALITY -- the program's single")
        print("  purchased assumption. With one degree of freedom the")
        print("  octonionic sector is not reduced but ABSENT: zero terms.")
        print("  The second generator takes the sweep to 5 dimensions and the")
        print("  term count to the full 14.")
    else:
        print("  The sector structure does NOT emerge from this law. What that")
        print("  rules out is recorded above; a defined construction would have")
        print("  to supply what this one does not.")


if __name__ == "__main__":
    main()
