#!/usr/bin/env python3
"""
z1_d8_attempt.py — Z1 ladder, rung D8: how far can it be closed in-house?
(Predictions stated before running.)

Construction: standard cyclic octonion table on units e1..e7 with Fano
lines {i, i+1, i+3} (mod 7, 1-indexed) — the SAME lines as s3_roles.py —
oriented cyclically: e_i e_{i+1} = e_{i+3} (+cyclic), anticommuting
otherwise, e_a^2 = -1.

PREDICTIONS:
 P0 sanity: norm composition |xy| = |x||y| on random octonions (machine).
 P1 CLIFFORD: {L_a, L_b} = -2 delta_ab on the 7 unit left-multiplications
    (exact) => transport generators are a Clifford system.
 P2 ARTIN: associator (a,b,x) == 0 whenever x lies in the subalgebra
    generated by {a,b} (machine zero); generically O(1) otherwise.
    Non-associativity is invisible to pairs; it first bites at triads.
 P3 TRIADIC CLOSURE + GRADING: for a Fano line {a,b,c}, the map
    G = -L_c^{-1} L_a L_b (sign convention measured, not assumed) has
    eigenvalues +/-1 with a 4+4 split, and its +1 eigenspace is exactly
    span{1, a, b, c}: two transports determine the third on their own
    quaternionic sector, anti-coherently on the complement.
 P4 GENERATED ALGEBRA: iterated commutators of {L_a} span dim 21 = spin(7)
    = the 21 unit pairs, partitioned by the 7 Fano lines (3 pairs each) —
    Steiner structure as generator bookkeeping. Bivectors project onto the
    7-dim octonionic-pulse family with nonzero residual: transport exits
    the algebra (the non-associative remainder is not transported).
 P5 CROWN CHECK (outcome genuinely unknown): the s3_roles Konig role
    table, read as cyclic line orientations (observer -> observed ->
    observation, i.e. ab = c around the cycle), defines a multiplication
    table. Test norm composition + alternativity for both global cyclic
    readings. YES => the role postulates are compatible with octonion
    structure; NO => the obstruction is the precise gap between the
    combinatorial and algebraic roads.
"""

import numpy as np
from itertools import permutations

LINES = [tuple(sorted(((i+s-1) % 7) + 1 for s in (0, 1, 3))) for i in range(1, 8)]
CYC = {}   # oriented products from cyclic construction: (a,b) -> (sign, c)

def build_table(oriented_lines):
    """oriented_lines: list of ordered triples (a,b,c) meaning ab=c cyclically."""
    T = {}
    for (a, b, c) in oriented_lines:
        for x, y, z in ((a,b,c), (b,c,a), (c,a,b)):
            T[(x, y)] = (1, z); T[(y, x)] = (-1, z)
    def mul(u, v):
        out = np.zeros(8)
        out[0] += u[0]*v[0] - np.dot(u[1:], v[1:])
        out[1:] += u[0]*v[1:] + v[0]*u[1:]
        for i in range(1, 8):
            for j in range(1, 8):
                if i == j: continue
                s, k = T[(i, j)]
                out[k] += s * u[i] * v[j]
        return out
    return mul

STD = [(i, (i % 7) + 1, ((i+2) % 7) + 1) for i in range(1, 8)]
mul = build_table(STD)

def Lmat(a):
    return np.column_stack([mul(a, np.eye(8)[j]) for j in range(8)])

def unit(i):
    v = np.zeros(8); v[i] = 1.0; return v

if __name__ == '__main__':
    rng = np.random.default_rng(7)
    # P0
    x, y = rng.normal(size=8), rng.normal(size=8)
    err = abs(np.linalg.norm(mul(x, y)) - np.linalg.norm(x)*np.linalg.norm(y))
    print(f'P0 norm composition residual: {err:.2e}')
    L = [None] + [Lmat(unit(i)) for i in range(1, 8)]
    # P1
    cmax = max(np.max(np.abs(L[i]@L[j] + L[j]@L[i] + 2*(i==j)*np.eye(8)))
               for i in range(1, 8) for j in range(1, 8))
    print(f'P1 Clifford residual: {cmax:.2e}')
    # P2
    a, b = rng.normal(size=8), rng.normal(size=8); a[0] = b[0] = 0
    ab = mul(a, b)
    assoc = lambda u, v, w: mul(mul(u, v), w) - mul(u, mul(v, w))
    in_alg = mul(a, ab) + 0.3*b + 0.2*a          # element of <a,b>
    print(f'P2 Artin: |(a,b,x)| for x in <a,b> = '
          f'{np.linalg.norm(assoc(a, b, in_alg)):.2e};  generic x = '
          f'{np.linalg.norm(assoc(a, b, rng.normal(size=8))):.3f}')
    # P3
    la, lb, lc = LINES[0]
    # orient per the standard table: find c and sign with e_la e_lb = s e_c
    s, c = ({(x,y): v for (x,y), v in
             [((i,j), None)] } if False else None), None
    prod = mul(unit(la), unit(lb)); k = int(np.argmax(np.abs(prod)))
    sgn = np.sign(prod[k])
    G = -sgn * np.linalg.inv(L[k]) @ L[la] @ L[lb]
    ev, V = np.linalg.eigh((G + G.T)/2)
    plus = V[:, ev > 0.5]
    plane = np.column_stack([unit(0), unit(la), unit(lb), unit(k)])
    # subspace angle between +1 eigenspace and quaternionic plane
    sv = np.linalg.svd(plus.T @ plane, compute_uv=False)
    print(f'P3 line {la,lb,k}: eigenvalues split '
          f'{np.sum(ev>0.5)}+{np.sum(ev<-0.5)}; +1-space vs span(1,a,b,c) '
          f'principal cosines min = {sv.min():.6f} (pred 1.000000)')
    # P4
    gens = [L[i] for i in range(1, 8)]
    basis = []
    def add(M):
        v = M.flatten()
        for b0 in basis: v = v - (v @ b0) * b0
        n = np.linalg.norm(v)
        if n > 1e-8: basis.append(v/n); return True
        return False
    frontier = list(gens)
    for M in frontier: add(M)
    for _ in range(3):
        new = []
        for A in gens:
            for B in frontier:
                Cm = A@B - B@A
                if add(Cm): new.append(Cm)
        frontier = new
        if not new: break
    print(f'P4 generated Lie algebra dim = {len(basis)}  (pred 21 = 7 lines x 3 pairs)')
    biv = L[1] @ L[2]
    span = np.column_stack([L[i].flatten() for i in range(1, 8)])
    coef, *_ = np.linalg.lstsq(span, biv.flatten(), rcond=None)
    res = np.linalg.norm(span @ coef - biv.flatten()) / np.linalg.norm(biv)
    print(f'   bivector residual off the octonionic-pulse family: {res:.3f} '
          f'(pred > 0: transport exits the algebra)')
    # P5 crown: Konig role coloring -> orientations -> valid algebra?
    ROLES = 3
    def color_fano():
        used = {p: set() for p in range(1, 8)}; assign = {}
        def bt(li):
            if li == len(LINES): return True
            Ln = LINES[li]
            for perm in permutations(range(3)):
                if all(perm[j] not in used[Ln[j]] for j in range(3)):
                    for j in range(3): used[Ln[j]].add(perm[j])
                    assign[Ln] = perm
                    if bt(li+1): return True
                    for j in range(3): used[Ln[j]].discard(perm[j])
                    del assign[Ln]
            return False
        bt(0); return assign
    A5 = color_fano()
    for reading, order in (('cyclic', (0,1,2)), ('anticyclic', (0,2,1))):
        oriented = []
        for Ln, perm in A5.items():
            seq = [Ln[perm.index(r)] for r in order]   # role order -> element order
            oriented.append(tuple(seq))
        mul5 = build_table(oriented)
        errs = []
        for _ in range(40):
            x, y = rng.normal(size=8), rng.normal(size=8)
            errs.append(abs(np.linalg.norm(mul5(x, y))
                            - np.linalg.norm(x)*np.linalg.norm(y)))
            errs.append(np.linalg.norm(mul5(mul5(x, x), y) - mul5(x, mul5(x, y))))
        print(f'P5 role-orientation table ({reading}): max norm/alternativity '
              f'violation = {max(errs):.3f}  '
              f'({"VALID octonion-type" if max(errs) < 1e-9 else "NOT a normed algebra"})')
