#!/usr/bin/env python3
"""
build_index.py — generate the claim index by SCANNING, not by recall

WHY THIS EXISTS. Every miss in this project has been a lookup failure, not a
reasoning failure:

  - u(3) was in the spec at line 113; a search of eight platform files for four
    keywords reported it absent.
  - The cone-reaches-D8 connection is the closing line of cone_vertex.py; it was
    lost and had to be recovered from memory.
  - A Henon-Heiles scope limit on Lemma 2.1 existed only in a transcript and was
    nearly lost entirely.
  - A coefficient was wrong by 10x, then by 2.6x, because a headline was written
    in prose rather than emitted by a script.

The common cause is that retrieval depended on whichever search terms happened
to occur to whoever was looking. An index fixes that and nothing else does.

THE RULE THIS FILE OBEYS: the index is generated by scanning every file. It is
never written from memory, because an index written from memory inherits the
exact failure it exists to cure.

WHAT IT EXTRACTS
  - every numeric claim in the documents, with file and line
  - every script, whether it runs, and what it prints
  - status markers: SUPERSEDED, RETRACTED, ERRATUM, FIX-, NotImplementedError
  - cross-references between documents
  - the numbers each script emits, for comparison against the documents

OUTPUT
  CLAIM_INDEX.json   machine-readable, for the consistency checker
  CLAIM_INDEX.md     human-readable

Python 3 stdlib only.
"""

import os
import re
import json
import subprocess
import sys

ROOT = "."
SKIP_DIRS = {".git", "__pycache__"}

# a "claim number" is a figure with enough precision to be a measurement
NUM = re.compile(
    r"(?<![\w.])"
    r"(\d+\.\d{2,}(?:[eE][-+]?\d+)?"       # 1.234, 4.62e-07
    r"|\d\.\d+[eE][-+]?\d+"                 # 1.1e-15
    r"|\d+/\d+"                             # 3/8
    r"|\d{2,})"                             # 128, 1540
    r"(?![\w.])"
)

STATUS = [
    ("RETRACTED", re.compile(r"retract", re.I)),
    ("SUPERSEDED", re.compile(r"supersede|SUPERSEDED", re.I)),
    ("ERRATUM", re.compile(r"erratum|ERRATUM", re.I)),
    ("WITHDRAWN", re.compile(r"withdraw", re.I)),
    ("OPEN", re.compile(r"\bopen\b|not measured|unresolved|not located", re.I)),
    ("PROVED", re.compile(r"\bproof\b|\bproved\b|\btheorem\b", re.I)),
    ("EXHAUSTIVE", re.compile(r"exhaustive", re.I)),
    ("VERIFIED", re.compile(r"verified|confirmed|MATCH|PASS", re.I)),
    ("SAMPLED", re.compile(r"sampled|samples|random", re.I)),
    ("FAILED", re.compile(r"\bFAIL|failed|MISS\b", re.I)),
]


def walk_files(ext):
    for r, d, f in os.walk(ROOT):
        d[:] = [x for x in d if x not in SKIP_DIRS]
        for x in sorted(f):
            if x.endswith(ext):
                yield os.path.join(r, x)


def scan_documents():
    out = []
    for p in walk_files(".md"):
        try:
            lines = open(p, encoding="utf-8", errors="replace").read().splitlines()
        except Exception:
            continue
        section = ""
        for i, ln in enumerate(lines, 1):
            if ln.startswith("#"):
                section = ln.lstrip("# ").strip()
            nums = NUM.findall(ln)
            if not nums:
                continue
            tags = [name for name, rx in STATUS if rx.search(ln)]
            out.append({
                "file": p, "line": i, "section": section,
                "text": ln.strip()[:220], "numbers": nums, "status": tags,
            })
    return out


def scan_scripts(run=False, timeout=90):
    out = []
    for p in walk_files(".py"):
        try:
            src = open(p, encoding="utf-8", errors="replace").read()
        except Exception:
            continue
        head = src[:2500]
        rec = {
            "file": p,
            "lines": len(src.splitlines()),
            "banner": "STATUS:" in head,
            "blocked": "NotImplementedError" in src,
            "fixes": sorted(set(re.findall(r"FIX-\d", src))),
            "predictions": len(re.findall(r"^\s*[A-Z]\d+\s", src, re.M)),
            "docstring": (src.split('"""')[1][:200].replace("\n", " ")
                          if '"""' in src else ""),
        }
        if run:
            try:
                r = subprocess.run([sys.executable, os.path.basename(p)],
                                   cwd=os.path.dirname(p) or ".",
                                   capture_output=True, text=True,
                                   timeout=timeout)
                rec["runs"] = (r.returncode == 0)
                rec["emits"] = sorted(set(NUM.findall(r.stdout)))[:40]
            except Exception:
                rec["runs"] = None
                rec["emits"] = []
        out.append(rec)
    return out


def main():
    run_scripts = "--run" in sys.argv
    docs = scan_documents()
    scripts = scan_scripts(run=run_scripts)

    index = {"documents": docs, "scripts": scripts,
             "counts": {"doc_claims": len(docs), "scripts": len(scripts)}}
    json.dump(index, open("00_START_HERE/CLAIM_INDEX.json", "w"), indent=1)

    # human-readable
    L = ["# Claim Index\n",
         "*Generated by `build_index.py` — scanned, not written from memory.*\n",
         f"\n{len(docs)} numeric claims across the documents; "
         f"{len(scripts)} scripts.\n"]

    bystatus = {}
    for d in docs:
        for s in (d["status"] or ["UNTAGGED"]):
            bystatus.setdefault(s, []).append(d)
    L.append("\n## Claims by status\n")
    for s in sorted(bystatus, key=lambda k: -len(bystatus[k])):
        L.append(f"- **{s}** — {len(bystatus[s])}")

    L.append("\n## Claims by document\n")
    byfile = {}
    for d in docs:
        byfile.setdefault(d["file"], []).append(d)
    for f in sorted(byfile):
        L.append(f"\n### `{f}` ({len(byfile[f])} claims)\n")
        for d in byfile[f][:400]:
            tag = ",".join(d["status"]) or "-"
            L.append(f"- L{d['line']} [{tag}] `{d['section'][:40]}` — "
                     f"{d['text'][:150]}")

    L.append("\n## Scripts\n")
    L.append("| file | lines | banner | blocked | fixes |")
    L.append("|---|---|---|---|---|")
    for s in scripts:
        L.append(f"| `{s['file']}` | {s['lines']} | "
                 f"{'yes' if s['banner'] else ''} | "
                 f"{'YES' if s['blocked'] else ''} | "
                 f"{','.join(s['fixes'])} |")

    open("00_START_HERE/CLAIM_INDEX.md", "w").write("\n".join(L) + "\n")
    print(f"  documents scanned : {len(byfile)}")
    print(f"  numeric claims    : {len(docs)}")
    print(f"  scripts scanned   : {len(scripts)}")
    print(f"  blocked scripts   : {sum(1 for s in scripts if s['blocked'])}")
    print(f"  bannered scripts  : {sum(1 for s in scripts if s['banner'])}")
    print("\n  status distribution:")
    for s in sorted(bystatus, key=lambda k: -len(bystatus[k])):
        print(f"    {s:12s} {len(bystatus[s])}")
    print("\n  wrote 00_START_HERE/CLAIM_INDEX.json and .md")


if __name__ == "__main__":
    main()
