#!/usr/bin/env python3
"""
anomalyE_purity.py -- anomaly E (census 2026-09-29): the isolated reference packet of
tower_populated_test.py (D8 = n 4, N = 128, node well, per-mode packet amp 0.05, width 8, n0 64,
T = 2000) lost chirality purity 0.9872 -> 0.9494 under the CARRIER readout (chi_low: chi = psi +
i dpsi / omega at the single carrier omega). Recomputed here with the per-mode readout
(model.readout_modes: purity = 1 - |b|/|a| per Fourier mode, constant in free evolution), on
the same run, both readouts side by side every 100 time units.
EXPECTATION (committed before the run): if the 0.038 loss is the single-carrier readout, the
per-mode purity starts at 1 - O(1e-3) and loses < 0.005 over T = 2000; a per-mode loss >= 0.005
would be real opposite-branch content generated by the nonlinearity.
usage: python3 anomalyE_purity.py -> anomalyE_purity_output.txt
"""
import os
import sys
os.environ.setdefault("OMP_NUM_THREADS", "1")
import numpy as np
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "04_scripts", "session"))
import model as M
import tower_populated_test as TP


def main():
    lat = M.Lattice(n=4, N=TP.N, well="node")
    u, v = lat.packet(amp=TP.AMP, n0=TP.N // 2, width=8.0, per_mode=True)
    lines = [f"anomaly E -- isolated reference packet (n 4, N {TP.N}, node well, amp {TP.AMP}, T {TP.T:.0f})",
             "      t   carrier purity (chi_low)   per-mode purity (readout_modes)"]
    t = 0.0
    while True:
        chi, bar = TP.chi_low(lat, u, v)
        pc = 1 - np.linalg.norm(bar) / np.linalg.norm(chi)
        _, pm = lat.readout_modes(u, v)
        lines.append(f"  {t:6.0f}   {pc:.5f}                   {pm:.6f}")
        print(lines[-1], flush=True)
        if t >= TP.T - 1e-9:
            break
        u, v, _ = lat.run(u, v, 100.0); t += 100.0
    open(os.path.join(os.path.dirname(os.path.abspath(__file__)), "anomalyE_purity_output.txt"), "w").write(
        "\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
