#!/usr/bin/env python3
"""
d8_theta.py -- tests of what could fix theta_ab (predictions: d8_theta_predictions.txt,
committed first, 40abe6d).

 O1  Artin: dimension of the subalgebra generated by a, b, and the associator on it, vs theta.
 O2  the generic flow's octonionic content (z1_d8_flow's span dimension and associator on
     the swept span) vs theta.
 G2  the spectrum of M = R_a + L_b depends on theta only (random pairs at equal theta).
 P2  is the lattice's J-sector complex structure JJ (n = 8) a one-sided multiplication in the
     residual sector's sedenion table (d16_spectrum_v2.cd(4))? If JJ = L_e then
     kappa JJ + C_r L_g = L_(kappa e + C_r g): one generator.

usage:  python3 d8_theta.py
"""
import importlib.util
import os
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
RUNGS = os.path.join(HERE, "..", "04_scripts", "rungs")
SESSION = os.path.join(HERE, "..", "04_scripts", "session")


def load(name, path):
    sp = importlib.util.spec_from_file_location(name, path)
    m = importlib.util.module_from_spec(sp)
    sp.loader.exec_module(m)
    return m


fl = load("fl", os.path.join(RUNGS, "z1_d8_flow.py"))
E8 = fl.oct_table(fl.ch.oriented_lines())


def unit_imag(rng, d=8):
    v = np.zeros(d); v[1:] = rng.normal(size=d - 1)
    return v / np.linalg.norm(v)


def pair(rng, th):
    a = unit_imag(rng)
    e = unit_imag(rng); e -= (e @ a) * a; e /= np.linalg.norm(e)
    t = np.radians(th)
    return a, np.cos(t) * a + np.sin(t) * e


def subalgebra(gens, E, tol=1e-10):
    """Span of the unital subalgebra generated by gens (closure under products)."""
    basis = []
    def add(v):
        w = v.copy()
        for b in basis:
            w -= (w @ b) * b
        n = np.linalg.norm(w)
        if n > tol:
            basis.append(w / n); return True
        return False
    add(np.eye(8)[0])
    for g in gens:
        add(g)
    grown = True
    while grown:
        grown = False
        for x in list(basis):
            for y in list(basis):
                grown |= add(fl.mul(x, y, E))
    return basis


def main():
    rng = np.random.default_rng(90)
    thetas = (1, 5, 30, 60, 76.345, 90, 120, 150, 179)
    print("O1  subalgebra generated by a, b (Artin) and the associator on it")
    for th in (0,) + thetas + (180,):
        a, b = pair(rng, th)
        B = subalgebra([a, b], E8)
        worst = max(np.linalg.norm(fl.assoc(x, y, z, E8)) for x in B for y in B for z in B)
        print(f"    theta {th:8.3f}: dim {len(B)}, max associator {worst:.1e}")

    print("\nO2  generic flow psi' = psi a + b psi: swept span dimension, associator on the span")
    p0 = unit_imag(rng); p0[0] = 0.4; p0 /= np.linalg.norm(p0)
    for th in (0,) + thetas + (180,):
        a, b = pair(rng, th)
        traj = fl.integrate(p0, lambda p: fl.mul(p, a, E8) + fl.mul(b, p, E8), T=40.0, n=8000)
        print(f"    theta {th:8.3f}: span dim {fl.span_dim(traj)[0]}, associator on span "
              f"{fl.assoc_on_span(traj, E8, rng)[0]:.3e}")

    print("\nG2  spectrum of M at equal theta, random pairs (max difference)")
    for th in (37.0, 90.0, 131.0):
        specs = []
        for _ in range(5):
            a, b = pair(rng, th)
            M = np.array([fl.mul(x, a, E8) + fl.mul(b, x, E8) for x in np.eye(8)]).T
            specs.append(np.sort(np.abs(np.linalg.eigvals(M).imag)))
        print(f"    theta {th:6.1f}: {max(np.abs(s - specs[0]).max() for s in specs):.1e}")

    print("\nP2  is the lattice's JJ a one-sided multiplication?")
    sys.path.insert(0, SESSION)
    import model as M
    v2 = load("v2", os.path.join(SESSION, "d16_spectrum_v2.py"))
    for n, E in ((8, v2.cd(4)), (4, v2.cd(3))):
        D = 2 * n
        JJ = M.rho(1j * np.eye(n))
        mul = lambda x, y: np.einsum("ijk,i,j->k", E, x, y)
        I = np.eye(D)
        hits = []
        for k in range(1, D):
            ek = I[k]
            Lk = np.array([mul(ek, x) for x in I]).T
            Rk = np.array([mul(x, ek) for x in I]).T
            for name, Op in (("L", Lk), ("R", Rk)):
                for sgn in (1, -1):
                    if np.abs(JJ - sgn * Op).max() < 1e-12:
                        hits.append(f"{'+' if sgn > 0 else '-'}{name}_e{k}")
        print(f"    n = {n} (D = {D}, table cd({int(np.log2(D))})): JJ equals {hits or 'no one-sided multiplication'}")
        if hits and hits[0][1] == "L":
            k = int(hits[0].split("e")[1]); s = 1 if hits[0][0] == "+" else -1
            g = unit_imag(rng, D) if D == 8 else np.r_[unit_imag(rng, 8), np.zeros(D - 8)]
            kap, Cr = 0.97, 0.05
            Lg = np.array([mul(g, x) for x in I]).T
            Lsum = np.array([mul(kap * s * I[k] + Cr * g, x) for x in I]).T
            print(f"       kappa JJ + C_r L_g - L_(kappa e + C_r g): {np.abs(kap * JJ + Cr * Lg - Lsum).max():.1e}")


if __name__ == "__main__":
    main()


def p2_general():
    """P2, extended after the first result (POST HOC, not in the committed predictions):
    is JJ = L_x, = R_y, or = L_x + R_y for ANY x, y (not only basis units)? Least squares
    over x, y; a zero residual would make kappa JJ + C_r L_g of the D8 form R_a + L_b."""
    sys.path.insert(0, SESSION)
    import model as M
    v2 = load("v2", os.path.join(SESSION, "d16_spectrum_v2.py"))
    print("\nP2+ (post hoc) best fit of JJ by L_x, R_y, L_x + R_y over all x, y")
    for n, E in ((8, v2.cd(4)), (4, v2.cd(3))):
        D = 2 * n
        JJ = M.rho(1j * np.eye(n)).ravel()
        Lb = np.stack([np.einsum("ijk,i->kj", E, np.eye(D)[i]).ravel() for i in range(D)], 1)
        Rb = np.stack([np.einsum("ijk,j->ki", E, np.eye(D)[i]).ravel() for i in range(D)], 1)
        for name, A in (("L_x", Lb), ("R_y", Rb), ("L_x + R_y", np.hstack([Lb, Rb]))):
            c, *_ = np.linalg.lstsq(A, JJ, rcond=None)
            print(f"    n = {n}: JJ vs {name:10s} relative residual {np.linalg.norm(A @ c - JJ) / np.linalg.norm(JJ):.3f}")


if __name__ == "__main__":
    p2_general()
