#!/usr/bin/env python3
# READING (B) VARIANT, ring (displacement from psi0 = (phi, 0)), generated by shape_zero_tests/ring_model.py -- not model.py
"""
model.py — the assembled Shape Zero model

ONE force law, parameterised by node size n, reproducing every verified result
that currently lives across three separate scripts with three node types.

    node state : u in R^(2n)   -- a cone point: radial (mass) x angular (shape)
    on-site    : -(x^2 - x - 1)          phi-well, fixed point at PHI
    intra-node : kappa * JJ * v          gyroscopic; SELECTS a complex structure
    inter-node : c*(x_+ + x_- - 2x)      elastic
                 + c*(W_n v_+ - W_- v_-)  gauge; W in u(n) by passivity

    n = 1  ->  u(1)     synthetic U(1), the pinned asymmetry
    n = 2  ->  u(2)     = u(1) + su(2), Pauli generators
    n = 3  ->  u(3)     = u(1) + su(3), Gell-Mann generators   [role triad]

Passivity forces W symmetric in the kinetic metric; symmetric plus JJ-commuting
is Hermitian on C^n, and that space is exactly u(n), dimension n^2. One theorem,
three node sizes.

BUILD GATES. Each step has a pass condition from MODEL_SPEC.md sec 7. The script
runs them in order and stops at the first failure, because a later gate means
nothing if an earlier one is broken.

    1  harness calibrated          locked routines refuse to report
    2  free propagation            energy drift < 1e-6
    3  complex structure           chirality purity ~0.98
    4  n=1 asymmetry               d_omega = -2 c beta sin k
    5  nonlinear regime            kappa = -0.0187 (0.0799 RETRACTED), beta-collapse
    6  n=2 ordering                59.86 deg vs 59.84 predicted
    7  n=3 ordering                65.12 deg vs 64.97 predicted
    8  Abelian control             ~0 at <=20-site segment separation

Everything here is verified elsewhere in the archive; this file is the assembly,
not new physics. Where a number differs from its source script it is because the
geometry differs (segment separation, readout time), and the gate compares
against theory rather than against a remembered number.

Python 3 + NumPy. Run:  python3 model.py
"""

import numpy as np
import sys
import os

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

# ----------------------------------------------------------------- constants
SQ5 = np.sqrt(5.0)
PHI = (1.0 + SQ5) / 2.0
C = 1.0
# Gyroscopic ratio: reference operating value kappa = kappa* = 2c/sqrt(K + 2c)
# = 0.971737, the floor derived from J-compatibility at every wavelength
# (MODEL_SPEC sec 3). The FLOOR is derived; setting kappa AT the floor is a
# CHOSEN operating point -- the value is a genuine parameter for experiment.
# Was 0.5 until 2026-09-25 (results at 0.5 superseded by the change of
# operating point, not retracted).
KAPPA = 2 * C / np.sqrt(SQ5 + 2 * C)
K0 = np.pi / 2
DT = 0.02


# ---- READING (B) VARIANT (shape_zero_tests/ring_model.py; not model.py) ----
RING_OFFSET = True


def _ring_xy(u):
    X = u[:, 0::2] + (PHI if RING_OFFSET else 0.0)
    Y = u[:, 1::2]
    return X, Y, np.sqrt(X * X + Y * Y)


def _ring_force(u):
    """-(x^2 - x - 1) psi / x per dimer, x = |psi|; zero at x = 0 exactly."""
    X, Y, x = _ring_xy(u)
    g = np.zeros_like(x)
    nz = x > 0
    g[nz] = -(x[nz] ** 2 - x[nz] - 1) / x[nz]
    out = np.empty_like(u)
    out[:, 0::2] = g * X
    out[:, 1::2] = g * Y
    return out


def _ring_V(u):
    """sum over dimers of V(x) - V(phi), V(x) = x^3/3 - x^2/2 - x."""
    _, _, x = _ring_xy(u)
    V = lambda z: z ** 3 / 3 - z ** 2 / 2 - z
    return float((V(x) - V(PHI)).sum())


# ------------------------------------------------------- representation layer
def rho(A):
    """Complex n x n -> real 2n x 2n. Dimension-agnostic; interleaved layout."""
    n = A.shape[0]
    M = np.zeros((2 * n, 2 * n))
    for j in range(n):
        for l in range(n):
            a = A[j, l]
            M[2 * j:2 * j + 2, 2 * l:2 * l + 2] = [[a.real, -a.imag],
                                                   [a.imag, a.real]]
    return M


def generators(n):
    """u(n) generators: Pauli for n=2, Gell-Mann for n=3, identity for n=1."""
    if n == 1:
        return [np.eye(1, dtype=complex)]
    if n == 2:
        return [np.array([[0, 1], [1, 0]], dtype=complex),
                np.array([[0, -1j], [1j, 0]]),
                np.array([[1, 0], [0, -1]], dtype=complex)]
    E = lambda i, j: (np.eye(n, dtype=complex)[:, [i]]
                      @ np.eye(n, dtype=complex)[[j], :])
    return [E(0, 1) + E(1, 0), -1j * (E(0, 1) - E(1, 0)), E(0, 0) - E(1, 1),
            E(0, 2) + E(2, 0), -1j * (E(0, 2) - E(2, 0)),
            E(1, 2) + E(2, 1), -1j * (E(1, 2) - E(2, 1)),
            (E(0, 0) + E(1, 1) - 2 * E(2, 2)) / np.sqrt(3)]


def gauge_class_dim(n):
    """Passivity: {W symmetric, [W,JJ]=0}. Must equal n^2 = dim u(n)."""
    D = 2 * n
    JJ = rho(1j * np.eye(n))
    basis = []
    for i in range(D):
        for j in range(i, D):
            M = np.zeros((D, D)); M[i, j] = 1.0; M[j, i] = 1.0
            basis.append(M)
    s = np.linalg.svd(np.array([(M @ JJ - JJ @ M).ravel() for M in basis]),
                      compute_uv=False)
    return len(basis) - int(np.sum((s > 1e-9 * s[0]) & (s > 1e-8)))


# ------------------------------------------------------------ the force law
class Lattice:
    """One force law for every node size."""

    def __init__(self, n, N=200, kappa=KAPPA, gyro_scalar=None,
                 C_r=0.0, tower=None, q=1, shape=None):
        """q = spatial dimension of the base. q=1 is the bench analogue;
        q=3 is what the ladder's principles admit (MODEL_SPEC sec 4)."""
        self.q = q
        if q == 1:
            self.shape = (N,)
        else:
            side = shape if shape else int(round(N ** (1.0 / q)))
            self.shape = (side,) * q
            N = side ** q
        self.n, self.N, self.D = n, N, 2 * n
        self.C_r = C_r                    # residual coupling strength
        self.tower = tower                # (E_table, g) for the residual sector
        self.kappa = kappa
        self.JJ = rho(1j * np.eye(n))
        self.G = generators(n)
        self.beta = gyro_scalar          # n=1 scalar sector, or None
        self.omega = 0.5 * (-kappa + np.sqrt(kappa ** 2 + 4 *
                            (SQ5 + 2 * C * (1 - np.cos(K0)))))

    def _lap(self, x):
        """Nearest-neighbour Laplacian over q spatial axes."""
        if self.q == 1:
            return np.roll(x, -1, axis=0) + np.roll(x, 1, axis=0) - 2 * x
        y = x.reshape(self.shape + (self.D,))
        out = np.zeros_like(y)
        for ax in range(self.q):
            out += np.roll(y, -1, axis=ax) + np.roll(y, 1, axis=ax) - 2 * y
        return out.reshape(x.shape)

    def _dirdiff(self, x, axis=0):
        """Antisymmetric nearest-neighbour difference along one axis."""
        if self.q == 1:
            return np.roll(x, -1, axis=0) - np.roll(x, 1, axis=0)
        y = x.reshape(self.shape + (self.D,))
        d = np.roll(y, -1, axis=axis) - np.roll(y, 1, axis=axis)
        return d.reshape(x.shape)

    def angular_momentum(self, u, v):
        """L_ij = sum_sites (x_i pi_j - x_j pi_i), the centrifugal source.

        pi_j is the MOMENTUM DENSITY along axis j: for a field, pi_j ~ v . d_j u.

        BUG FIXED HERE: an earlier version used a SCALAR density p and formed
        x_i p x_j - x_j p x_i, which is identically zero for any input --
        everything commutes. The function could only ever return 0, and gate 10
        passed it because that gate checks the tensor's SHAPE, not that it is
        non-trivial. This matters: angular momentum is the one DIMENSIONFUL
        conserved quantity the model has ([L] = M L^2 / T = M L at c=1, the
        dimensions of action), and at q = 1 it is identically zero because
        so(1) = 0.
        """
        if self.q < 2:
            return np.zeros((1, 1))
        coords = np.indices(self.shape).reshape(self.q, -1).astype(float)
        for a in range(self.q):
            coords[a] -= coords[a].mean()
        y = u.reshape(self.shape + (self.D,))
        # momentum density along each spatial axis
        pi = []
        for a in range(self.q):
            du = (np.roll(y, -1, axis=a) - np.roll(y, 1, axis=a)) / 2.0
            pi.append((v * du.reshape(self.N, self.D)).sum(axis=1))
        L = np.zeros((self.q, self.q))
        for i2 in range(self.q):
            for j2 in range(self.q):
                L[i2, j2] = float(np.sum(coords[i2] * pi[j2]
                                         - coords[j2] * pi[i2]))
        return L

    def _shift(self, x, s, axis=0):
        """Shift by s sites along a SPATIAL axis.

        BUG FIXED HERE: for q > 1 the state is stored flat as (N, D) with
        N = side**q in C-ordering, so np.roll(x, s, axis=0) shifts by one
        entry of the FLATTENED index -- which is the LAST spatial axis, not
        the first. The gauge terms were coupling along axis q-1 while the
        packet propagated along axis 0. The elastic term was already correct
        because it went through _lap.
        """
        if self.q == 1:
            return np.roll(x, s, axis=0)
        y = x.reshape(self.shape + (self.D,))
        return np.roll(y, s, axis=axis).reshape(x.shape)

    def force(self, u, v, W=None, Wm=None):
        vp, vm = self._shift(v, -1), self._shift(v, 1)
        f = _ring_force(u) + C * self._lap(u)
        if self.kappa:
            f = f + self.kappa * (v @ self.JJ.T)
        if self.beta:                                   # scalar gauge sector
            f = f - self.beta * C * (vp - vm)
        if W is not None:                               # matrix gauge sector
            f = f + C * (np.einsum('nab,nb->na', W, vp)
                         - np.einsum('nab,nb->na', Wm, vm))
        if self.C_r and self.tower is not None:         # RESIDUAL sector
            Et, g = self.tower
            f = f + self.C_r * np.einsum('ijk,i,nj->nk', Et, g, v)  # velocity form: does no work
        return f

    # ---------------------------------------------------------- cone state
    # MODEL_SPEC sec 0: the node state is a CONE point -- a radial (mass)
    # coordinate and an angular (shape) coordinate. The HK cone metric is
    #     ds^2 = dr^2 + r^2 d(theta)^2
    # so the ANGULAR metric scale is r^2 = m, the mass. That is the one
    # relation in the architecture linking the two coordinates, and a flat
    # R^(2n) node cannot express it.

    def cone_split(self, u):
        """Split the node state into (mass m, unit shape sigma).

        m = |u|^2 is the radial/mass coordinate; sigma = u/|u| the angular
        shape on the unit sphere. Returns (m, sigma) per site.
        """
        nr = np.linalg.norm(u, axis=1)
        m = nr ** 2
        sig = np.zeros_like(u)
        nz = nr > 1e-30
        sig[nz] = u[nz] / nr[nz, None]
        return m, sig

    def cone_metric_scale(self, u):
        """The angular metric scale at each site: k = r^2 = m.

        This is the HK cone relation. Integrality on the fundamental cycle
        then requires Area/(2 pi) = k to be an integer, i.e. the node mass is
        QUANTISED in cone units (MODEL_SPEC sec 4c).
        """
        m, _ = self.cone_split(u)
        return m

    def cone_energy(self, u, v):
        """Energy in cone coordinates: radial + angular parts, separately.

        Checks that the split is faithful -- the two parts must sum to the
        kinetic energy computed in flat coordinates.
        """
        nr = np.linalg.norm(u, axis=1)
        nz = nr > 1e-30
        rdot = np.zeros(self.N)
        rdot[nz] = (u[nz] * v[nz]).sum(axis=1) / nr[nz]      # radial velocity
        K_r = 0.5 * (rdot ** 2).sum()
        K_tot = 0.5 * (v * v).sum()
        return K_r, K_tot - K_r                              # radial, angular

    def residual_B(self, u):
        """The residual scalar per node. 0 where the state is octonionic."""
        if self.tower is None:
            return np.zeros(self.N)
        out = np.empty(self.N)
        for i in range(self.N):
            a = u[i]
            nr = np.linalg.norm(a)
            if nr < 1e-30:
                out[i] = 0.0
                continue
            a = a / nr
            h = len(a) // 2
            p, q = a[:h], a[h:]
            u1, u2 = p[0], q[0]
            u3, u4 = p @ p, p @ q
            out[i] = (u3 - u1 ** 2) * ((1 - u3) - u2 ** 2) - (u4 - u1 * u2) ** 2
        return out

    def energy(self, u, v):
        """Total energy. The gradient term must sum over ALL q spatial axes --
        using the 1D form on a q-dimensional lattice measures the wrong
        quantity and produces a fixed apparent drift insensitive to timestep."""
        if self.q == 1:
            grad = ((np.roll(u, -1, axis=0) - u) ** 2).sum()
        else:
            y = u.reshape(self.shape + (self.D,))
            grad = sum(((np.roll(y, -1, axis=ax) - y) ** 2).sum()
                       for ax in range(self.q))
        return (0.5 * (v * v).sum() + _ring_V(u) + 0.5 * C * grad)

    def step_rk4(self, u, v, W, Wm):
        f = lambda uu, vv: self.force(uu, vv, W, Wm)
        k1v, k1u = f(u, v), v
        k2v, k2u = f(u + .5 * DT * k1u, v + .5 * DT * k1v), v + .5 * DT * k1v
        k3v, k3u = f(u + .5 * DT * k2u, v + .5 * DT * k2v), v + .5 * DT * k2v
        k4v, k4u = f(u + DT * k3u, v + DT * k3v), v + DT * k3v
        return (u + DT / 6 * (k1u + 2 * k2u + 2 * k3u + k4u),
                v + DT / 6 * (k1v + 2 * k2v + 2 * k3v + k4v))

    def packet(self, amp=1e-3, n0=20, width=8.0, colour=0, per_mode=False):
        """Localised positive-frequency packet on a q-dimensional base.

        per_mode=True (used by gate 3 and ordering_test -- gates 7 and 8 -- since
        2026-09-25): every Fourier mode is launched at its own chi-branch frequency,
        w^2 + kappa w = Q(k), Q(k) = sqrt5 + 2c sum(1 - cos k), so the packet carries
        no opposite-branch content. per_mode=False (the default, kept for the gates
        that test node-level structure: the carrier launch is purely angular at
        every site, a per-mode launch is not) is the CARRIER launch (every mode at
        self.omega): it leaves off-branch content that makes the carrier-omega readout oscillate in time, and two runs
        read at unequal times then differ although their dynamics commute (MODEL_SPEC
        sec 4d.1, traps 6 and 7). The scalar-beta sector keeps the carrier launch
        (its branch is not w^2 + kappa w = Q)."""
        if self.q == 1:
            x = np.arange(self.N)
            env = np.exp(-0.5 * ((x - n0) / width) ** 2)
            ph = K0 * (x - n0)
        else:
            side = self.shape[0]
            w = min(width, side / 4.0)
            c = np.indices(self.shape).astype(float)
            r2 = np.zeros(self.shape)
            for a in range(self.q):
                d = c[a] - side / 2.0
                d = (d + side / 2) % side - side / 2      # periodic distance
                r2 += d ** 2
            env = np.exp(-0.5 * r2 / w ** 2).reshape(-1)
            d0 = (c[0] - side / 2.0)
            d0 = (d0 + side / 2) % side - side / 2
            ph = (K0 * d0).reshape(-1)
        u = np.zeros((self.N, self.D)); v = np.zeros((self.N, self.D))
        ur, ui = amp * env * np.cos(ph), amp * env * np.sin(ph)
        u[:, 2 * colour] = ur
        u[:, 2 * colour + 1] = ui
        if per_mode and not self.beta:
            psi = (ur + 1j * ui).reshape(self.shape)
            om = self.branch_omega()
            dpsi = np.fft.ifftn(-1j * om * np.fft.fftn(psi)).reshape(-1)
            v[:, 2 * colour] = dpsi.real
            v[:, 2 * colour + 1] = dpsi.imag
        else:
            v[:, 2 * colour] = self.omega * ui
            v[:, 2 * colour + 1] = -self.omega * ur
        return u, v

    def branch_omega(self):
        """chi-branch frequency of every Fourier mode of self.shape:
        w^2 + kappa w = sqrt5 + 2c sum_a (1 - cos k_a)."""
        k = np.meshgrid(*[2 * np.pi * np.fft.fftfreq(m) for m in self.shape],
                        indexing="ij")
        Qk = SQ5 + 2 * C * sum(1 - np.cos(ka) for ka in k)
        return 0.5 * (-self.kappa + np.sqrt(self.kappa ** 2 + 4 * Qk))

    def readout_modes(self, u, v):
        """Per-mode chirality split -- a diagnostic, not used by the gates.

        readout() splits chiralities with the single carrier frequency
        (chi = psi + i dpsi / omega). Per Fourier mode the field is
        a e^{-i w_a t} + b e^{+i w_b t}, w_a^2 + kappa w_a = Q, w_b = w_a + kappa, so
            a = (w_b psi + i dpsi) / (w_a + w_b),  b = (w_a psi - i dpsi) / (w_a + w_b).
        Returns (coords, purity) in readout()'s form, from sum_k a_k a_k^+ and
        purity = 1 - |b| / |a|; both are constant in free evolution."""
        wa = self.branch_omega()
        wb = wa + self.kappa
        ax = tuple(range(len(self.shape)))
        psi = (u[:, 0::2] + 1j * u[:, 1::2]).reshape(self.shape + (self.n,))
        dps = (v[:, 0::2] + 1j * v[:, 1::2]).reshape(self.shape + (self.n,))
        P, D = np.fft.fftn(psi, axes=ax), np.fft.fftn(dps, axes=ax)
        a = ((wb[..., None] * P + 1j * D) / (wa + wb)[..., None]).reshape(-1, self.n)
        b = ((wa[..., None] * P - 1j * D) / (wa + wb)[..., None]).reshape(-1, self.n)
        rs = a.T @ a.conj()
        tr = np.real(np.trace(rs)) + 1e-30
        co = np.array([np.real(np.trace(S @ rs)) / tr for S in self.G])
        pur = float(np.clip(1 - np.linalg.norm(b) / (np.linalg.norm(a) + 1e-30), 0, 1))
        return co, pur

    def readout(self, u, v):
        """Density matrix over the whole lattice; coords + chirality purity."""
        psi = u[:, 0::2] + 1j * u[:, 1::2]
        dps = v[:, 0::2] + 1j * v[:, 1::2]
        chi = psi + (1j / self.omega) * dps
        bar = psi - (1j / self.omega) * dps
        rs = chi.T @ chi.conj()
        tr = np.real(np.trace(rs)) + 1e-30
        co = np.array([np.real(np.trace(S @ rs)) / tr for S in self.G])
        pur = float(np.clip(1 - np.linalg.norm(bar) /
                            (np.linalg.norm(chi) + 1e-30), 0, 1))
        return co, pur

    def run(self, u, v, T, W=None, Wm=None):
        E0 = self.energy(u, v)
        for _ in range(int(T / DT)):
            u, v = self.step_rk4(u, v, W, Wm)
        return u, v, abs(self.energy(u, v) - E0) / (abs(E0) + 1e-30)


# ------------------------------------------------- segment geometry (gates 7-8)
RAMP = [0.25, 0.5, 0.75] + [1.0] * 6 + [0.75, 0.5, 0.25]


def make_links(lat, spec):
    """Gauge links. spec = [(start, axis, strength), ...]

    The segment is a SLAB perpendicular to the propagation axis (axis 0):
    every site whose axis-0 coordinate is start+j carries the same link.

    BUG FIXED HERE: W[(start+j) % N] indexes the FLATTENED array, so on a
    q>1 lattice a 'segment' was 12 consecutive flat entries -- a line along
    the LAST axis, not a slab perpendicular to the first. And np.roll(W, 1,
    axis=0) for Wm was likewise a flat roll.
    """
    W = np.zeros((lat.N, lat.D, lat.D))
    if lat.q == 1:
        for start, axis, g in spec:
            R = rho(lat.G[axis])
            for j, wgt in enumerate(RAMP):
                W[(start + j) % lat.N] = g * wgt * R
        return W, np.roll(W, 1, axis=0)
    side = lat.shape[0]
    Wg = W.reshape(lat.shape + (lat.D, lat.D))
    for start, axis, g in spec:
        R = rho(lat.G[axis])
        for j, wgt in enumerate(RAMP):
            Wg[(start + j) % side, ...] = g * wgt * R
    Wm = np.roll(Wg, 1, axis=0).reshape(lat.N, lat.D, lat.D)
    return Wg.reshape(lat.N, lat.D, lat.D), Wm


def transverse_Q(lat, u, v):
    """Transverse contribution to the dispersion, 2c * sum_t (1 - cos k_t).

    On a q>1 lattice the elastic term is 2c sum_i (1 - cos k_i), so a packet
    with transverse content shifts the branch wavenumber. The 1-D k_branch
    solves the wrong equation; over two segments the mean-k_t correction
    alone accumulates ~70 deg of phase, which is the size of the observed
    sim-vs-pred offsets.

    Measured power-weighted, so a narrow spread gives one meaningful number.
    """
    if lat.q == 1:
        return 0.0
    y = u.reshape(lat.shape + (lat.D,))
    tot = 0.0
    for ax in range(1, lat.q):
        F = np.abs(np.fft.fft(y, axis=ax)) ** 2
        P = F.sum(axis=tuple(a for a in range(lat.q + 1) if a != ax))
        kk = 2 * np.pi * np.fft.fftfreq(lat.shape[ax])
        if P.sum() <= 0:
            continue
        tot += 2 * C * float((P * (1 - np.cos(kk))).sum() / P.sum())
    return tot


def k_branch(lat, g_eig, Qt=0.0):
    """Branch wavenumber. Qt is the transverse dispersion contribution."""
    w = lat.omega
    Q = w * w + lat.kappa * w - SQ5 - Qt
    f = lambda k: 2 * C * (1 - np.cos(k)) - 2 * C * g_eig * w * np.sin(k) - Q
    lo, hi = 0.2, np.pi - 0.2
    for _ in range(80):
        mid = 0.5 * (lo + hi)
        if f(lo) * f(mid) <= 0:
            hi = mid
        else:
            lo = mid
    return 0.5 * (lo + hi)


def U_segment(lat, axis, g_max, Qt=0.0):
    """Independent prediction: spectral projectors, one per eigenvalue.

    Works for ANY node size. The u(2) case has two eigenvalues +-1 and is the
    degenerate instance; su(3) generators have three.
    """
    eigs, vecs = np.linalg.eigh(lat.G[axis])
    U = np.eye(lat.n, dtype=complex)
    for wgt in RAMP:
        P = [np.outer(vecs[:, j], vecs[:, j].conj()) for j in range(lat.n)]
        U = sum(np.exp(1j * k_branch(lat, g_max * wgt * eigs[j], Qt)) * P[j]
                for j in range(lat.n)) @ U
    return U


def coords_of_state(lat, psi):
    r = np.outer(psi, psi.conj())
    tr = np.real(np.trace(r)) + 1e-30
    return np.array([np.real(np.trace(S @ r)) / tr for S in lat.G])


def angle(c1, c2):
    n1, n2 = np.linalg.norm(c1), np.linalg.norm(c2)
    if n1 < 1e-12 or n2 < 1e-12:
        return 0.0
    return np.degrees(np.arccos(np.clip(c1 @ c2 / (n1 * n2), -1, 1)))


def ordering_test(n, gA, gB, seg=(60, 80), T=180.0, q=1, side=None,
                  width=None, n0=None, axes=(0, 1)):
    """Two segments in both orders; compare against independent prediction.

    q = 1 (default): the verified chain protocol, N = 200, segments (60, 80).

    q = 3: REQUIRES, per MODEL_SPEC sec 4d --
      * a FULL transverse slab (make_links does this for q > 1)
      * segments non-overlapping: they must be >= len(RAMP) = 12 apart
      * post-exit readout, certified by CUMULATIVE displacement, never
        modular position (a dispersed packet defeats argmax as well as
        wrap detection)
    A tube narrower than the packet's transverse support clips it and
    suppresses the rotation: 0.885 (slab) -> 0.582 (r=4) -> 0.270 (r=2.5).
    """
    if q == 1:
        lat = Lattice(n=n, N=200)
        width = width or 8.0
        n0 = n0 if n0 is not None else 20
    else:
        side = side or 32
        assert seg[1] - seg[0] >= len(RAMP), (
            f"segments must be >= {len(RAMP)} apart or they overlap")
        lat = Lattice(n=n, N=side ** q, q=q)
        width = width or 1.5
        n0 = n0 if n0 is not None else 1
    a0, a1 = axes
    psi0 = np.zeros(n, dtype=complex); psi0[0] = 1.0
    out = {}
    for name, spec, order in (
            ("AB", [(seg[0], a0, gA), (seg[1], a1, gB)], (1, 0)),
            ("BA", [(seg[0], a1, gB), (seg[1], a0, gA)], (0, 1))):
        W, Wm = make_links(lat, spec)
        u, v = lat.packet(width=width, n0=n0, per_mode=True)
        u, v, drift = lat.run(u, v, T, W, Wm)
        co, pur = lat.readout(u, v)
        Qt = transverse_Q(lat, u, v)
        gs = (gA, gB) if order == (1, 0) else (gB, gA)
        ax = (a0, a1) if order == (1, 0) else (a1, a0)
        Upred = U_segment(lat, ax[1], gs[1], Qt) @ U_segment(lat, ax[0], gs[0], Qt)
        out[name] = (co, coords_of_state(lat, Upred @ psi0), pur, drift)
    return out


def run_until_exit(lat, u, v, seg_start, W, Wm, T_max=200.0, dT=2.0):
    """Evolve until the packet has CLEARED the segment, certified by cumulative
    displacement. Returns (u, v, drift, cum_disp, cleared).

    WHY THIS EXISTS. Modular position CANNOT detect wrap-around: a packet that
    has crossed the far boundary reports a small index and looks like it never
    moved. Worse, a dispersed packet defeats argmax entirely -- residual
    amplitude near the launch point can outweigh the travelling peak. Both
    failure modes produced wrong q=3 results in this programme: a packet that
    had traversed the segment TWICE was read as a single clean pass, and the
    resulting numbers were reported as a physical q=1 vs q=3 difference before
    being retracted.

    The fix is to accumulate centroid motion step by step and unwrap it, so the
    total distance travelled is known regardless of how many times the packet
    has crossed the boundary.

    KNOWN INSUFFICIENT (found later): a CENTROID past the segment does not mean
    the packet has LEFT it -- the tail can still be inside. ~3% of the packet
    remaining manufactured a ~1e-3 floor in the J-compatibility test and biased
    segment rotations by up to 0.39 deg. MEASURED AT q = 3: this certificate
    fires with 98% of the packet still inside the segment windows, and the
    resulting ~1 deg Abelian floor is exactly 0 under a clearing readout. The correct certificate is the WEIGHT
    remaining in the segment window falling below ~1e-6. Use `cleared` here as a
    necessary condition only, and check segment-window weight before reading out.

    AT q = 3 IT FIRES FAR TOO EARLY (measured, shape_zero_tests/q3_readout.py,
    320 x 12 x 12 slab, width-3 packet, segments at 50 and 70): the centroid
    passes seg_end + 2 at t ~ 116 with ~98% of the packet weight still inside
    the segment windows [start - 10, start + len(RAMP) + 10); the 1e-6 weight
    certificate is not met until t ~ 340. Read out at this point, the Abelian
    floor is ~1 deg (0.000 deg once cleared), and the split's apparent agreement
    with the single-wavenumber product (2.4 / 0.06 deg) is a coincidence of the
    mid-exit readout. The q = 3 ordering gate (shape_zero_tests/q3_gate.py)
    reads out on the window-weight certificate instead.
    """
    side = lat.shape[0] if lat.q > 1 else lat.N
    seg_end = seg_start + len(RAMP)

    def centroid(uu):
        w = np.linalg.norm(uu, axis=1) ** 2
        if lat.q > 1:
            w = w.reshape(lat.shape).sum(axis=tuple(range(1, lat.q)))
        ang = 2 * np.pi * np.arange(side) / side          # circular mean, so a
        z = (w * np.exp(1j * ang)).sum()                  # packet straddling the
        if abs(z) < 1e-30:                                # seam is handled
            return 0.0
        return (np.angle(z) % (2 * np.pi)) * side / (2 * np.pi)

    cum = 0.0
    prev = centroid(u)
    start = prev
    t = 0.0
    E0 = lat.energy(u, v)
    while t < T_max:
        u, v, _ = lat.run(u, v, dT, W, Wm)
        t += dT
        cur = centroid(u)
        step = cur - prev
        if step < -side / 2:          # forward wrap
            step += side
        elif step > side / 2:         # backward wrap
            step -= side
        cum += step
        prev = cur
        if start + cum > seg_end + 2.0:
            break
    drift = abs(lat.energy(u, v) - E0) / (abs(E0) + 1e-30)
    cleared = (start + cum) > seg_end
    return u, v, drift, cum, cleared


def abelian_floor(n, gA, gB, **kw):
    """The instrument's zero: SAME axis, DIFFERENT strengths, both orders.

    Commuting matrices, so the algebra says the splitting is 0. What remains is
    kinematic -- unequal strengths give different group velocities, hence
    different arrival profiles. Measured ~1.4 deg at q = 3.

    NOTE: equal strengths make the two specs the SAME ARRAY. That control
    cannot fail and returned 0.000 deg three separate times before being
    caught. Always use DIFFERENT strengths here.
    """
    assert abs(gA - gB) > 1e-12, "equal strengths make this control vacuous"
    r = ordering_test(n, gA, gB, axes=(0, 0), **kw)
    return angle(r["AB"][0], r["BA"][0])


# --------------------------------------------------------------- build gates
def gate(step, name, ok, detail):
    mark = "PASS" if ok else "FAIL"
    print(f"  [{mark}] {step}. {name}")
    print(f"         {detail}")
    return True   # [variant copy] report every gate


def main():
    print("=" * 68)
    print("SHAPE ZERO — ASSEMBLED MODEL")
    print("=" * 68)
    print()

    # ---- 1 harness -----------------------------------------------------
    try:
        import harness
        okc = harness.calibrate_all(verbose=False)
        rep = harness.CALIBRATION_REPORT
        d = ", ".join(f"{k}:{'pass' if v[1] else 'LOCKED'}"
                      for k, v in rep.items())
        if not gate(1, "harness calibrated", "freq_phase" in
                    {k for k, v in rep.items() if v[1]}, d):
            return
    except ImportError:
        gate(1, "harness calibrated", False, "harness.py not importable")
        return

    # ---- 2 free propagation -------------------------------------------
    lat = Lattice(n=1, kappa=0.0)
    u, v = lat.packet()
    u, v, drift = lat.run(u, v, T=60.0)
    if not gate(2, "free propagation", drift < 1e-6,
                f"energy drift {drift:.2e}  (need < 1e-6)"):
        return

    # ---- 3 complex structure -------------------------------------------
    lat = Lattice(n=2)
    u, v = lat.packet(per_mode=True)
    u, v, drift = lat.run(u, v, T=60.0)
    _, pur = lat.readout(u, v)
    if not gate(3, "complex structure selected", pur > 0.95,
                f"chirality purity {pur:.4f}  drift {drift:.2e}"):
        return

    # ---- 4 gauge class dimension ---------------------------------------
    dims = {n: gauge_class_dim(n) for n in (1, 2, 3, 4, 5)}
    ok = all(dims[n] == n * n for n in dims)
    gate(4, "passivity gives u(n), dim n^2", ok,
         "  ".join(f"n={n}:{dims[n]}" for n in sorted(dims)))

    # ---- 5 n=1 asymmetry, MEASURED from evolved packets -----------------
    beta = 0.05
    th = -2 * C * beta * np.sin(K0)
    import importlib.util
    refp = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                        "pinned_asymmetry_reference.py")
    sp = importlib.util.spec_from_file_location("ref", refp)
    ref = importlib.util.module_from_spec(sp)
    sp.loader.exec_module(ref)
    d_lin, q_lin = ref.delta(beta, 0.02)
    gate(5, "n=1 asymmetry, MEASURED", abs(abs(d_lin) - abs(th)) < 2e-3,
         f"|d_omega| {abs(d_lin):.6f}   -2 c beta sin k = {abs(th):.6f}   "
         f"resid {q_lin:.3f}")

    # ---- 6 the A^2 law and the beta-collapse ---------------------------
    ks = []
    for b in (0.02, 0.05, 0.10, 0.20):
        d, _ = ref.delta(b, 0.30)
        t = -2 * C * b * np.sin(K0)
        # SIGNED: the old abs() could not report a shrinking asymmetry.
        ks.append((abs(d) - abs(t)) / abs(t) / 0.09)
    kap, spread = float(np.mean(ks)), float(np.std(ks))
    gate(6, "kappa and the beta-collapse", spread < 2e-3,
         f"kappa {kap:.4f} +/- {spread:.5f} across a tenfold beta range "
         f"(corrected: -0.0187; 0.0799 retracted, seeding swap)")

    # ---- 7 u(2) and u(3) ordering --------------------------------------
    # ---- 7 ordering: CONTROL-SUBTRACTED criterion (MODEL_SPEC sec 4d) ----
    # q = 3 counterpart: shape_zero_tests/q3_gate.py (too slow for main();
    # clearing readout, spectrum-averaged prediction).
    # The unitary product is NOT the pass object. Applying U2 to the MEASURED
    # mid-state gives 3.7/5.9 deg, WORSE than the plain product's 3.1/3.2 --
    # global composition of internal unitaries is the wrong object once the
    # packet has spatial structure. The gate instead uses the Abelian floor as
    # the instrument's zero and asks whether the non-commuting split exceeds it.
    for nn, gA, gB, lbl in ((2, 0.12, 0.08, "u(2)"), (3, 0.15, 0.10, "u(3)")):
        r = ordering_test(nn, gA, gB)
        mAB, pAB, pur, dr = r["AB"]; mBA, pBA, _, _ = r["BA"]
        ms = angle(mAB, mBA)
        floor = abelian_floor(nn, gA, gB)
        excess = ms - floor
        # CRITERION REVISED. The earlier test "split > 10 x Abelian floor" is
        # VACUOUS at q = 1: under a clearing readout the floor is exactly 0
        # (its ~0.016 deg was the packet's tail still inside the second segment
        # -- 16-18% of the weight at this T), so the ten-times test cannot fail.
        # At q = 1 the meaningful test is the split against the INDEPENDENT
        # prediction, which passes at 0.2-0.45 deg. The floor stays as a sanity
        # check that CAN fail: commuting segments must not produce a split.
        dAB, dBA = angle(mAB, pAB), angle(mBA, pBA)
        psplit = angle(pAB, pBA)
        ok = (dAB < 1.0 and dBA < 1.0 and abs(ms - psplit) < 1.0
              and floor < 0.5)
        gate(7, f"{lbl} ordering vs independent prediction", ok,
             f"split {ms:.2f} deg vs predicted {psplit:.2f} deg | "
             f"per-order {dAB:.2f} / {dBA:.2f} deg | Abelian floor "
             f"{floor:.3f} deg (algebra: 0) | drift {dr:.1e}")

    # ---- 8 Abelian control is now gate 7's own zero ----------------------
    fl = abelian_floor(2, 0.12, 0.08)
    gate(8, "Abelian control (commuting axes, unequal strengths)", fl < 3.0,
         f"{fl:.4f} deg   (theory 0; equal strengths would be vacuous)")

    # ---- 9 cone state (MODEL_SPEC sec 0) --------------------------------
    lat = Lattice(n=3, N=200, q=1)
    u, v = lat.packet(amp=1e-2)
    m, sig = lat.cone_split(u)
    nz = m > 1e-20
    sp_err = np.abs(np.linalg.norm(sig[nz], axis=1) - 1).max()
    Kr, Ka = lat.cone_energy(u, v)
    en_err = abs(Kr + Ka - 0.5 * (v * v).sum())
    gate(9, "cone state: radial/angular split", sp_err < 1e-12 and en_err < 1e-12,
         f"|sigma|-1 max {sp_err:.1e}, energy split residual {en_err:.1e}, "
         f"radial K {Kr:.2e} vs angular {Ka:.2e}")

    # ---- 10 q-dimensional base (MODEL_SPEC sec 4) -----------------------
    rows = []
    for q, side in ((1, 512), (2, 22), (3, 10)):
        N = side if q == 1 else side ** q
        lb = Lattice(n=2, N=N, q=q)
        uu, vv = lb.packet(amp=1e-3, width=side / 4.0 if q > 1 else 8.0)
        uu, vv, dq = lb.run(uu, vv, T=20.0)
        soq = q * (q - 1) // 2
        rows.append((q, lb.N, dq, soq))
    ok = all(d < 1e-6 for _, _, d, _ in rows)
    gate(10, "base runs at q = 1, 2, 3 with so(q) angular momentum", ok,
         "  ".join(f"q={q}:{N} sites drift {d:.1e} so({q})={s}"
                   for q, N, d, s in rows))

    # ---- 11 residual sector coexists with the base ----------------------
    try:
        import importlib.util
        sp = importlib.util.spec_from_file_location("v2", "d16_spectrum_v2.py")
        v2m = importlib.util.module_from_spec(sp); sp.loader.exec_module(v2m)
        E16 = v2m.cd(4)
        rg = np.random.default_rng(5)
        gv = np.zeros(16); gv[1:8] = rg.normal(size=7); gv /= np.linalg.norm(gv)
        out = []
        for q, N in ((1, 512), (3, 512)):
            for Cr in (0.0, 0.05):
                lr = Lattice(n=8, N=N, q=q, kappa=0.0, C_r=Cr, tower=(E16, gv))
                uu, vv = lr.packet(amp=1e-3)
                uu[:, 8:] += 0.3 * uu[:, :8]
                uu, vv, dq = lr.run(uu, vv, T=20.0)
                out.append((q, Cr, dq, lr.residual_B(uu).mean()))
        inert = all(abs(B) < 1e-12 for q, Cr, d, B in out if Cr == 0)
        alive = all(abs(B) > 1e-6 for q, Cr, d, B in out if Cr > 0)
        gate(11, "residual: inert at C_r=0, active otherwise, at q=1 and q=3",
             inert and alive,
             "  ".join(f"q={q} C_r={c}: B={B:.2e}" for q, c, d, B in out))
    except Exception as e:
        gate(11, "residual sector", False, f"could not run: {e}")

    print()
    print("=" * 68)
    print("  THE MODEL PREDICTS")
    print("=" * 68)
    print(f"    d_omega(k, A) = -2 c beta sin(k) * [ 1 {'+' if kap >= 0 else '-'} {abs(kap):.4f} A^2 ]")
    print()
    print("    the coefficient is beta-INDEPENDENT, so the normalised drift")
    print("    collapses across coupling strengths. That collapse is the")
    print("    experiment: one knob, two observables, no fitted parameter.")
    print()
    print("    resolution needed: ~1e-4 for the pinning, ~1e-5 for the A^2 law")
    print("    valid amplitude:   A below ~0.9")
    print()
    print("    ** kappa = 0.0799 is RETRACTED (reference seeded each direction")
    print("    with the other's root); corrected plane-wave / 1-D value -0.0187. **")
    print("    The plane-wave kappa = -0.0187 is the ONLY real coefficient.")
    print("    A localised beam's box-averaged kappa depends on the box size")
    print("    and goes to zero as the box grows. kappa(w = 2, side) is CLOSED:")
    print("    a static fixed dilution, kappa_box = kappa_pw * fill * F, with")
    print("    F = 2 - s holding within error for L >= 12 (MODEL_SPEC sec 5).")
    print("    Quote a localised kappa only with its box size. The w = 3 value")
    print("    and the geometry table remain UNVERIFIED.")
    print("    The PINNING is width-independent at every configuration tested.")
    print("=" * 68)


if __name__ == "__main__":
    main()
