#!/usr/bin/env python3
"""octonionic_u1_check.py -- (2026-09-26, report check) does the octonionic 3-form c (the tensor in the
octonionic term) commute with the U(1) generated by J = L_e (multiplication by a chosen unit e, splitting
O = C + C^3)? Splits c into the part with an index along e (the Kaehler form omega, charge 0) and the
rest (Re Omega, the C^3 volume form, charge 3). Also: parity of the 7D-base (3,3) term T under a
single-axis base reflection, full inversion, and target orientation reversal. Needs scipy.
usage: python3 octonionic_u1_check.py"""
import os; os.chdir(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
import importlib.util, numpy as np
s=importlib.util.spec_from_file_location('fl','04_scripts/rungs/z1_d8_flow.py');fl=importlib.util.module_from_spec(s);s.loader.exec_module(fl)
E=fl.oct_table(fl.ch.oriented_lines())
c=E[1:,1:,1:]                     # structure constants on Im(O): e_a e_b = -delta + c_abk e_k
print("c totally antisymmetric:", np.abs(c+c.transpose(1,0,2)).max(), np.abs(c+c.transpose(0,2,1)).max())
# U(1)_J: J = L_e on Im(O) with e = e_1 (fixes e, rotates the 6-plane e-perp)
L = np.einsum('ijk,i->kj', E, np.eye(8)[1])[1:,1:]   # left mult by e1 restricted to Im(O)
print("L_e maps Im(O)->Im(O) on e-perp: L e1 =", np.round(L[:,0],3), " L^2 on e-perp = -1:", np.abs((L@L)[1:,1:]+np.eye(6)).max())
Jp = L.copy(); Jp[:,0]=0; Jp[0,:]=0                  # J on e-perp, zero on e
def rot(th): 
    from scipy.linalg import expm
    return expm(th*Jp)
tr = lambda R: np.einsum('ai,bj,ck,ijk->abc', R, R, R, c)
for th in (0.3, np.pi/3, 2*np.pi/3, np.pi/2):
    R = rot(th); print(f"theta {th:.4f}: |c(R.,R.,R.) - c| / |c| = {np.linalg.norm(tr(R)-c)/np.linalg.norm(c):.3e}")
# charge decomposition: split c into parts with one index = e (omega piece) and none (Re Omega piece)
ce = np.zeros_like(c); idx=[0]
mask1 = np.zeros((7,7,7),bool); mask1[0,:,:]=mask1[:,0,:]=mask1[:,:,0]=True
c_omega = np.where(mask1, c, 0); c_Omega = np.where(mask1, 0, c)
for th in (0.3, np.pi/2):
    R=rot(th); 
    print(f"theta {th:.3f}: omega part invariant {np.linalg.norm(tr(R)*mask1 - c_omega):.1e}; ReOmega part change {np.linalg.norm(np.where(mask1,0,tr(R))-c_Omega)/np.linalg.norm(c_Omega):.3f} (charge 3 predicts |e^{{3i th}}-1|/sqrt2 ~ {abs(np.exp(3j*th)-1)/np.sqrt(2):.3f})")
# (3,3) T on a 7D base: single-axis base reflection
rng=np.random.default_rng(1); J=rng.normal(size=(7,7))
T=lambda J: np.einsum('mnr,abc,ma,nb,rc->',c,c,J,J,J)
Rb=np.eye(7); Rb[3,3]=-1
print("T(J) =", T(J), " T(Rb J) =", T(Rb@J), " T(-J) =", T(-J), " T with c->-c on target only:", np.einsum('mnr,abc,ma,nb,rc->',c,-c,J,J,J))
