#!/usr/bin/env python3
"""
radial_model.py -- build and run a RADIAL-WELL variant of 04_scripts/session/model.py,
without changing model.py.

model.py's on-site force is -(sqrt5 u + u*u) with the square taken per REAL
COMPONENT (and the matching energy sum(u^3)/3). The variant replaces the
nonlinear part, per dimer psi_j = u_{2j} + i u_{2j+1}, by the same well acting on
the dimer's radius r_j = |psi_j| and pointing along psi_j:

    V_j = sqrt5 r_j^2 / 2 + r_j^3 / 3,   F_j = -(sqrt5 + r_j) psi_j

i.e. the phi-well's displacement expansion (sqrt5 r + r^2) applied to r = |psi|.
The linear part (sqrt5) is unchanged, so every linear result is unchanged; only
the nonlinearity differs. F_j(e^{i theta} psi) = e^{i theta} F_j(psi): the J sector
gains an exact U(1) symmetry (phase charge conserved at every order).

Two textual substitutions, each required to match exactly once:
    force : "f = -(SQ5 * u + u * u) + C * self._lap(u)"
            -> "f = -(SQ5 * u + _radial_sq(u)) + C * self._lap(u)"
    energy: "+ (u ** 3).sum() / 3" -> "+ (_dimer_r(u) ** 3).sum() / 3"
plus the two helper functions, inserted after "DT = 0.02".

usage:  python3 radial_model.py build          -> writes shape_zero_tests/model_radial.py
        python3 radial_model.py gates          -> runs model_radial.py's gates (from
                                                  04_scripts/session, like model.py)
"""
import os
import runpy
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
SESSION = os.path.join(HERE, "..", "04_scripts", "session")
SRC = os.path.join(SESSION, "model.py")
OUT = os.path.join(HERE, "model_radial.py")

HELPERS = '''

# ---- RADIAL-WELL VARIANT (shape_zero_tests/radial_model.py; not model.py) ----
def _dimer_r(u):
    """|psi_j| for every dimer j of every site: shape (N, D/2)."""
    return np.sqrt(u[:, 0::2] ** 2 + u[:, 1::2] ** 2)


def _radial_sq(u):
    """Nonlinear part of the radial well: r_j * psi_j per dimer (replaces u*u)."""
    r = _dimer_r(u)
    out = np.empty_like(u)
    out[:, 0::2] = r * u[:, 0::2]
    out[:, 1::2] = r * u[:, 1::2]
    return out
'''


def build():
    s = open(SRC).read()
    subs = [("f = -(SQ5 * u + u * u) + C * self._lap(u)",
             "f = -(SQ5 * u + _radial_sq(u)) + C * self._lap(u)"),
            ("+ (u ** 3).sum() / 3", "+ (_dimer_r(u) ** 3).sum() / 3"),
            ("DT = 0.02\n", "DT = 0.02\n" + HELPERS)]
    for old, new in subs:
        if s.count(old) != 1:
            raise SystemExit(f"model.py: expected exactly one {old!r}")
        s = s.replace(old, new)
    first, rest = s.split("\n", 1)
    s = first + "\n# RADIAL-WELL VARIANT generated by shape_zero_tests/radial_model.py -- not model.py\n" + rest
    open(OUT, "w").write(s)
    return s


def gates():
    s = build()
    with tempfile.NamedTemporaryFile("w", suffix="_model_radial.py", dir=SESSION, delete=False) as f:
        f.write(s)
        path = f.name
    try:
        print("=== model.py gates with the RADIAL well (radial_model.py) ===", flush=True)
        sys.path.insert(0, SESSION)
        os.chdir(SESSION)
        runpy.run_path(path, run_name="__main__")
    finally:
        os.remove(path)


if __name__ == "__main__":
    {"build": build, "gates": gates}[sys.argv[1]]()
