#!/usr/bin/env python3
"""
ring_model.py -- reading (B): the phi-well acting on the RADIUS x = |psi| of each
dimer, minimum on the ring |psi| = phi, as MODEL_SPEC §0 describes the node ("an
unbounded displacement in a phi-well -- that is the radial coordinate"). Generated
copies of 04_scripts/session/model.py; model.py itself is not changed.

Per dimer j, psi_j = X + i Y with (X, Y) the node coordinates:
    x = |psi_j|,   V(x) = x^3/3 - x^2/2 - x   (V'(x) = x^2 - x - 1, zeros phi, -1/phi)
    F_j = -(x^2 - x - 1) psi_j / x
x >= 0, so only the root phi is reachable: the minimum is the ring x = phi,
V''(phi) = 2 phi - 1 = sqrt5. At x = 0 the force has magnitude 1, points outward,
and has no defined direction: the origin is NOT an equilibrium (set to 0 there).

Two copies:
  ring    -- u is the DISPLACEMENT from the ring point psi0 = (phi, 0) of every
             dimer: X = phi + u_{2j}, Y = u_{2j+1}. u = 0 is an equilibrium, as in
             model.py (where u is the displacement from x = phi). This is the only
             way model.py's gates -- all built on small u around 0 -- can run.
  literal -- psi = u directly (no offset): the gates' small-amplitude states sit
             at the origin, which is not an equilibrium.
Both copies let every gate report (gate() returns True after printing its verdict)
so a failure does not hide the gates after it; the printed PASS/FAIL is the gate's
own criterion, unchanged.

usage:  python3 ring_model.py build            -> model_ring.py, model_ring_literal.py
        python3 ring_model.py gates ring|literal
"""
import os
import runpy
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
SESSION = os.path.join(HERE, "..", "04_scripts", "session")
SRC = os.path.join(SESSION, "model.py")

HELPERS = '''

# ---- READING (B) VARIANT (shape_zero_tests/ring_model.py; not model.py) ----
RING_OFFSET = {offset}


def _ring_xy(u):
    X = u[:, 0::2] + (PHI if RING_OFFSET else 0.0)
    Y = u[:, 1::2]
    return X, Y, np.sqrt(X * X + Y * Y)


def _ring_force(u):
    """-(x^2 - x - 1) psi / x per dimer, x = |psi|; zero at x = 0 exactly."""
    X, Y, x = _ring_xy(u)
    g = np.zeros_like(x)
    nz = x > 0
    g[nz] = -(x[nz] ** 2 - x[nz] - 1) / x[nz]
    out = np.empty_like(u)
    out[:, 0::2] = g * X
    out[:, 1::2] = g * Y
    return out


def _ring_V(u):
    """sum over dimers of V(x) - V(phi), V(x) = x^3/3 - x^2/2 - x."""
    _, _, x = _ring_xy(u)
    V = lambda z: z ** 3 / 3 - z ** 2 / 2 - z
    return float((V(x) - V(PHI)).sum())
'''


def build_one(offset, out):
    s = open(SRC).read()
    subs = [("f = -(SQ5 * u + u * u) + C * self._lap(u)", "f = _ring_force(u) + C * self._lap(u)"),
            ("0.5 * SQ5 * (u * u).sum()\n                + (u ** 3).sum() / 3", "_ring_V(u)"),
            ("DT = 0.02\n", "DT = 0.02\n" + HELPERS.format(offset=offset)),
            ("    print(f\"         {detail}\")\n    return ok\n",
             "    print(f\"         {detail}\")\n    return True   # [variant copy] report every gate\n")]
    for old, new in subs:
        if s.count(old) != 1:
            raise SystemExit(f"model.py: expected exactly one {old!r}")
        s = s.replace(old, new)
    first, rest = s.split("\n", 1)
    tag = "ring (displacement from psi0 = (phi, 0))" if offset else "literal (psi = u, no offset)"
    s = first + f"\n# READING (B) VARIANT, {tag}, generated by shape_zero_tests/ring_model.py -- not model.py\n" + rest
    open(os.path.join(HERE, out), "w").write(s)
    return s


def build():
    return {"ring": build_one(True, "model_ring.py"), "literal": build_one(False, "model_ring_literal.py")}


def gates(which):
    s = build()[which]
    with tempfile.NamedTemporaryFile("w", suffix=f"_model_{which}.py", dir=SESSION, delete=False) as f:
        f.write(s)
        path = f.name
    try:
        print(f"=== model.py gates, reading (B), {which} copy (every gate reports) ===", flush=True)
        sys.path.insert(0, SESSION)
        os.chdir(SESSION)
        runpy.run_path(path, run_name="__main__")
    finally:
        os.remove(path)


if __name__ == "__main__":
    if sys.argv[1] == "build":
        build()
    else:
        gates(sys.argv[2])
