#!/usr/bin/env python3
"""
a2_invariance_hinge.py — A-2, restricted and tested
(Shape Zero open threads item A-2; also settles A-3 as a census)

A-2 asks whether the program may apply its selection principles to STRUCTURE
rather than to states within structure. Leg (i) of the argument is:

    a coupling is constructible from the structure already present
        <=>  it is invariant under that structure's automorphism group

The forward direction is trivial. The REVERSE is the content, and it is false
as a general principle: "every invariant is generated by the obvious ones" is
a First Fundamental Theorem, and FFTs hold per group and per representation,
not universally. So A-2 cannot be justified as a scope extension. It can be
RESTRICTED to the cases where the program actually uses it, and checked there.

Where the program uses it, the structure is the octonions and the group is
G2 = Aut(O), acting on Im(O) = R^7. This script tests leg (i) there.

METHOD. For each of the 128 sign assignments of the 7 Fano lines:
  - test whether the resulting algebra is a composition algebra (|xy|=|x||y|)
  - compute its derivation algebra (the Lie algebra of Aut)
  - compute the space of invariant tensors at ranks 2, 3, 4 as the joint
    kernel of the derivation action
  - compare against the CONSTRUCTIBLE tensors -- those built only from the
    metric d_ij and the structure constants c_ijk

PREDICTIONS STATED BEFORE RUNNING
 R1 exactly 16 of the 128 sign patterns give composition algebras.
    (Independent reproduction of the z1_d8_census.py count.)
 R2 every valid algebra has a 14-dimensional derivation algebra (= g2).
    (Reproduces z1_hinge.py's single instance across the whole census -> A-3.)
 R3 rank 2: invariant space is 1-dimensional, spanned by the metric.
 R4 rank 3: invariant space is 1-dimensional, and proportional to c itself
    (|normalized overlap| = 1 to 1e-10) for EVERY valid algebra.
 R5 rank 4: invariant space is 4-dimensional, and lies entirely in the span
    of the four constructible tensors
        d_ij d_kl,  d_ik d_jl,  d_il d_jk,  sum_m c_ijm c_klm
    (projection residual <= 1e-10). Rank 4 is the first rank where a
    non-constructible invariant could hide, so this is the real test:
    dim(invariant) > dim(constructible) at any rank REFUTES leg (i).

Python 3 + NumPy only. Runtime ~3 min (rank 4 dominates).
"""

import numpy as np

TOL = 1e-10


# ---------------------------------------------------------------- algebra
def fano_lines():
    """Quadratic-residue Fano plane: (i, i+1, i+3) mod 7."""
    return [((i) % 7, (i + 1) % 7, (i + 3) % 7) for i in range(7)]


def structure_constants(signs):
    """Totally antisymmetric c[i,j,k] from oriented Fano lines."""
    c = np.zeros((7, 7, 7))
    for (a, b, d), s in zip(fano_lines(), signs):
        for (x, y, z), sg in [((a, b, d), 1), ((b, d, a), 1), ((d, a, b), 1),
                              ((b, a, d), -1), ((a, d, b), -1), ((d, b, a), -1)]:
            c[x, y, z] = s * sg
    return c


def mult(x, y, c):
    """Octonion product in 8D: x = (x0, xv)."""
    x0, xv = x[0], x[1:]
    y0, yv = y[0], y[1:]
    r0 = x0 * y0 - xv @ yv
    rv = x0 * yv + y0 * xv + np.einsum('ijk,i,j->k', c, xv, yv)
    return np.concatenate([[r0], rv])


def is_composition(c, trials=6, seed=0):
    """Normed division algebra test: |xy| = |x||y|."""
    rng = np.random.default_rng(seed)
    for _ in range(trials):
        x, y = rng.normal(size=8), rng.normal(size=8)
        lhs = np.linalg.norm(mult(x, y, c))
        rhs = np.linalg.norm(x) * np.linalg.norm(y)
        if abs(lhs - rhs) > 1e-9 * max(1.0, rhs):
            return False
    return True


# ---------------------------------------------------------------- derivations
def derivations(c):
    """Basis of {D : D(xy) = D(x)y + xD(y)} on Im(O), as 7x7 matrices.

    Condition, coefficient of e_k in D(e_i e_j) = D(e_i)e_j + e_i D(e_j):
        sum_m c[i,j,m] D[k,m] - sum_m D[m,i] c[m,j,k] - sum_m D[m,j] c[i,m,k] = 0
    """
    rows = []
    for i in range(7):
        for j in range(7):
            for k in range(7):
                M = np.zeros((7, 7))
                M[k, :] += c[i, j, :]
                M[:, i] -= c[:, j, k]
                M[:, j] -= c[i, :, k]
                rows.append(M.ravel())
    A = np.array(rows)
    _, s, Vt = np.linalg.svd(A)
    thresh = max(A.shape) * np.finfo(float).eps * (s[0] if s.size else 1.0)
    null = Vt[np.sum(s > max(thresh, TOL)):]
    return [v.reshape(7, 7) for v in null]


# ---------------------------------------------------------------- invariants
def invariant_space(gens, rank):
    """Joint kernel of the Lie algebra action on V^{tensor rank}."""
    n = 7 ** rank
    I7 = np.eye(7)
    A = np.zeros((n, n))
    for X in gens:
        L = np.zeros((n, n))
        for slot in range(rank):
            mats = [I7] * rank
            mats[slot] = X
            K = mats[0]
            for M in mats[1:]:
                K = np.kron(K, M)
            L += K
        A += L.T @ L
    w, V = np.linalg.eigh(A)
    scale = max(w[-1], 1.0)
    keep = w < TOL * scale
    return V[:, keep]


def constructible(c, rank):
    """Tensors built only from the metric and the structure constants."""
    d = np.eye(7)
    if rank == 2:
        return [d]
    if rank == 3:
        return [c]
    if rank == 4:
        return [np.einsum('ij,kl->ijkl', d, d),
                np.einsum('ik,jl->ijkl', d, d),
                np.einsum('il,jk->ijkl', d, d),
                np.einsum('ijm,klm->ijkl', c, c)]
    raise ValueError(rank)


def residual_outside_span(basis_cols, tensors):
    """Max component of the invariant space orthogonal to the constructibles."""
    B = np.array([t.ravel() for t in tensors]).T
    Q, _ = np.linalg.qr(B)
    resid = basis_cols - Q @ (Q.T @ basis_cols)
    return np.max(np.abs(resid)) if basis_cols.size else 0.0


# ---------------------------------------------------------------- run
def main():
    print("=" * 70)
    print("A-2 :: INVARIANCE HINGE, RESTRICTED TO G2 ON R^7")
    print("=" * 70)

    valid = []
    for mask in range(128):
        signs = [1 if (mask >> b) & 1 == 0 else -1 for b in range(7)]
        c = structure_constants(signs)
        if is_composition(c):
            valid.append((mask, c))

    print(f"\nR1  composition algebras: {len(valid)} of 128"
          f"   [predicted 16 -> {'PASS' if len(valid) == 16 else 'MISS'}]")

    print("\nR2/R3/R4  derivations and low-rank invariants, per algebra")
    print("-" * 70)
    print("  mask   dim(Der)   inv(r2)   inv(r3)   |overlap with c|")
    ok2 = ok3 = ok4 = True
    ders = {}
    for mask, c in valid:
        D = derivations(c)
        ders[mask] = D
        i2 = invariant_space(D, 2)
        i3 = invariant_space(D, 3)
        ov = 0.0
        if i3.shape[1] == 1:
            v = i3[:, 0]
            cv = c.ravel() / np.linalg.norm(c.ravel())
            ov = abs(v @ cv)
        ok2 &= (len(D) == 14)
        ok3 &= (i2.shape[1] == 1 and i3.shape[1] == 1)
        ok4 &= (abs(ov - 1.0) < 1e-8)
        print(f"   {mask:3d}      {len(D):3d}       {i2.shape[1]:3d}"
              f"       {i3.shape[1]:3d}      {ov:.10f}")

    print(f"\n  R2 dim(Der) = 14 for all : {'PASS' if ok2 else 'MISS'}")
    print(f"  R3 rank-2 and rank-3 = 1 : {'PASS' if ok3 else 'MISS'}")
    print(f"  R4 rank-3 invariant is c : {'PASS' if ok4 else 'MISS'}")

    print("\nR5  RANK 4 -- the real test")
    print("-" * 70)
    print("  mask   dim(invariant)   dim(constructible)   residual outside span")
    ok5 = True
    for mask, c in valid:
        i4 = invariant_space(ders[mask], 4)
        cons = constructible(c, 4)
        B = np.array([t.ravel() for t in cons]).T
        dcons = np.linalg.matrix_rank(B, tol=1e-10)
        res = residual_outside_span(i4, cons)
        ok5 &= (i4.shape[1] == dcons and res < 1e-8)
        print(f"   {mask:3d}         {i4.shape[1]:3d}                {dcons:3d}"
              f"                 {res:.3e}")

    print(f"\n  R5 every rank-4 invariant is constructible : "
          f"{'PASS' if ok5 else 'MISS'}")

    print("\n" + "=" * 70)
    print("READING")
    print("=" * 70)
    print("  A PASS restricts leg (i) to a verified statement about G2 on R^7")
    print("  at ranks <= 4. It does NOT establish the general scope extension,")
    print("  which is false as a general principle. A MISS at rank 4 would")
    print("  refute leg (i) outright where the program uses it.")


if __name__ == "__main__":
    main()
