#!/usr/bin/env python3
"""
d8_crossing_trigger.py — what actually switches the 8 cross-sector terms on?

d8_sector_selection.py found 6 non-null terms inside a Fano line and 14 across,
and a scan over unions of lines showed the jump is a step function: two lines
(5 points) already give the full 14. That scan was coarse. It only ever tested
supports built as unions of LINES, so it could not separate two hypotheses:

  (a) the trigger is DIMENSION -- enough independent directions
  (b) the trigger is ASSOCIATIVITY FAILURE -- the support ceasing to lie in a
      single quaternion subalgebra

Artin separates them. Any TWO imaginary units generate an associative
subalgebra, and for octonion basis units that subalgebra is exactly the Fano
line through them. So three points ON a line are associative; three points OFF
any line are not, while having the same dimension count. Scanning all C(7,3) =
35 triples therefore tests (a) against (b) at fixed support size.

An earlier framing of this task -- "are the 8 terms generated by the
associator" -- is ill-posed and is not attempted. A (3,4) term carries seven
indices, psi is a 4-form, and 7 - 4 = 3 cannot be paired by deltas, so NO
(3,4) invariant can carry psi. The associator, which is proportional to psi,
cannot appear in these terms at all.

PREDICTIONS STATED BEFORE RUNNING
 N1 the 7 collinear triples reproduce 9 / 3 / 6.
 N2 the 28 non-collinear triples give a strictly higher non-null count at the
    SAME support size, isolating associativity rather than dimension as the
    trigger.
 N3 predict the non-collinear triples give the full 14, since three generic
    imaginary units generate all of O.
    [N2 and N3 BOTH MISSED, and backwards. Non-collinear triples give ZERO.
    Every (3,4) invariant carries exactly one phi, and phi_{ijk} is nonzero
    only on Fano lines, so a support containing no complete line restricts phi
    to zero and every term vanishes. The trigger is not associativity failure
    but CONTAINMENT OF A COMPLETE LINE.

    A finer scan over all supports also refutes the "step function" claim made
    from the earlier unions-of-lines scan: 4 points containing one line give
    13, an intermediate value. That scan only sampled unions of lines, which
    jump from 3 points to 5, so the intermediate case was invisible to it.

      pts  lines inside  non-null
       3        0            0
       3        1            6
       4        0            0
       4        1           13
       5        2           14
      6-7      4-7          14

    Corrected reading: containing a complete Fano line is a hard threshold
    (zero versus non-zero); above it the count grows with support and
    saturates at 14 by five points.]
 N4 the split is clean: every triple gives either the collinear value or the
    non-collinear value, with nothing in between.

Python 3 + NumPy only. Uses d8_channels.py for the shared machinery.
"""

import numpy as np
import importlib.util
import os
from itertools import combinations

_here = os.path.dirname(os.path.abspath(__file__))
spec = importlib.util.spec_from_file_location(
    "ch", os.path.join(_here, "d8_channels.py"))
ch = importlib.util.module_from_spec(spec)
spec.loader.exec_module(ch)

FANO = [tuple(sorted((((i + s - 1) % 7)) for s in (0, 1, 3))) for i in range(7)]
LINESET = {frozenset(l) for l in FANO}


def projector(points):
    P = np.zeros((7, 7))
    for i in points:
        P[i, i] = 1.0
    return P


def counts(rng, NS, T34, CUR, c, I7, P=None):
    J = rng.normal(size=(NS, 7, 7))
    H = rng.normal(size=(NS, 7, 7, 7))
    H = 0.5 * (H + np.transpose(H, (0, 2, 1, 3)))
    if P is not None:
        J = np.einsum('ij,zjk,kl->zil', P, J, P)
        H = np.einsum('ij,zjkl,km,ln->zimn', P, H, P, P)
    A = np.stack([ch.eval_34(t, J, H, c, I7) for t in T34], axis=1)
    B = np.stack([ch.eval_div(v, J, H, c, I7) for v in CUR], axis=1)
    return ch.rank(A), ch.rank(B)


def main():
    orient = ch.oriented_lines()
    c = ch.imaginary_c(orient)
    I7 = np.eye(7)
    T34, CUR = ch.terms_34(), ch.currents()
    rng = np.random.default_rng(113)
    NS = 200
    print("=" * 70)
    print("WHAT TRIGGERS THE CROSS-SECTOR TERMS?")
    print("=" * 70)

    full = counts(rng, NS, T34, CUR, c, I7)
    print(f"\n  unrestricted : dim {full[0]}  div {full[1]}  "
          f"non-null {full[0] - full[1]}")

    coll, noncoll = {}, {}
    for tri in combinations(range(7), 3):
        ra, rb = counts(rng, NS, T34, CUR, c, I7, projector(tri))
        key = (ra, rb, ra - rb)
        if frozenset(tri) in LINESET:
            coll[key] = coll.get(key, 0) + 1
        else:
            noncoll[key] = noncoll.get(key, 0) + 1

    print("\n  ALL 35 TRIPLES OF POINTS, SAME SUPPORT SIZE")
    print("-" * 70)
    print("    collinear (on a Fano line), 7 triples:")
    for k, n in sorted(coll.items()):
        print(f"      dim {k[0]:3d}  div {k[1]:3d}  non-null {k[2]:3d}"
              f"   x{n}")
    print("    NON-collinear, 28 triples:")
    for k, n in sorted(noncoll.items()):
        print(f"      dim {k[0]:3d}  div {k[1]:3d}  non-null {k[2]:3d}"
              f"   x{n}")

    ok1 = list(coll.keys()) == [(9, 3, 6)]
    nn_non = {k[2] for k in noncoll}
    ok2 = min(nn_non) > 6
    ok3 = nn_non == {full[0] - full[1]}
    ok4 = len(coll) == 1 and len(noncoll) == 1
    print(f"\n    N1 collinear give 9/3/6            : "
          f"{'PASS' if ok1 else 'MISS'}")
    print(f"    N2 non-collinear strictly higher    : "
          f"{'PASS' if ok2 else 'MISS'}")
    print(f"    N3 non-collinear give the full {full[0]-full[1]:2d}   : "
          f"{'PASS' if ok3 else 'MISS'}")
    print(f"    N4 clean two-valued split           : "
          f"{'PASS' if ok4 else 'MISS'}")

    print("\n" + "=" * 70)
    print("READING")
    print("=" * 70)
    if ok2 and ok4:
        print("  The trigger is ASSOCIATIVITY, not dimension. Three points of")
        print("  identical support size give 6 terms when they lie on a Fano")
        print("  line and the full count when they do not. Nothing about the")
        print("  size of the support distinguishes the two cases.")
        print()
        print("  Combined with the associator being 0 or exactly 4 and nothing")
        print("  between, the rung is discrete in the same way twice over:")
        print("  a configuration either lies in a quaternion subalgebra or it")
        print("  does not, and everything switches on the instant it does not.")
    else:
        print("  The split is not clean -- see the failing line above.")


if __name__ == "__main__":
    main()
