#!/usr/bin/env python3
"""
d8_exact_verification.py — Theorem 5.1 without floating point

Review note on ShapeZero_C1_Formal_Proofs.pdf, Section 5. The document offers
two justifications side by side:

    "direct evaluation of the 28 independent components of the polarised
     bilinear form, OR by sampling random vectors to machine precision and
     confirming residuals below 1e-14"

Those are different epistemic standards. The first is exact and exhaustive;
the second is numerical evidence. A document whose abstract says "every
structural claim is proved below" should not rest a Theorem on the second.

This script supplies the first, in INTEGER arithmetic with no floating point
anywhere, so the count of 16 is a decision rather than a measurement. (The
same critique applies to my own is_composition() in the C1S scripts, which
samples; this replaces it for the orientation count.)

EXACT CRITERION. Let L_a be left multiplication by e_a on O = R^8, entries in
{-1, 0, +1}. The algebra is a composition algebra iff the Clifford relations

    L_a L_b + L_b L_a = -2 delta_ab I

hold. These are integer matrix identities, checkable exactly. The document
itself notes this fact in Section 5 but does not use it as the criterion.

PREDICTIONS STATED BEFORE RUNNING
 X1 in exact integer arithmetic, exactly 16 of the 128 orientations satisfy
    the Clifford relations. No sampling, no tolerance.
 X2 the exact set coincides with the set found by norm multiplicativity, so
    the sampled criterion was not wrong -- only weaker than advertised.
 X3 PARTITION CLAIM, Section 5: "the Lie algebra generated by the L_a is
    21-dimensional and partitioned by the seven lines (three bivectors per
    line)." Predict TRUE, and predict it is immediate rather than an
    enumeration output: the 21 bivectors L_a L_b (a<b) are indexed by the 21
    PAIRS of imaginary units, and a Steiner triple system puts every pair in
    exactly one line. 21 pairs / 7 lines = 3 per line is the Steiner property
    restated, not a separate discovery.
 X4 the seven 3-dimensional blocks are mutually orthogonal in the trace form
    and sum to 21, so "partition" is literally correct and not merely
    "spanned".

Python 3 + NumPy only.
"""

import numpy as np
from itertools import permutations

FANO = [tuple(sorted((((i + s - 1) % 7) + 1) for s in (0, 1, 3)))
        for i in range(1, 8)]


def table_int(signs):
    """Octonion multiplication as an exact integer array."""
    E = np.zeros((8, 8, 8), dtype=np.int64)
    E[0, :, :] = np.eye(8, dtype=np.int64)
    E[:, 0, :] = np.eye(8, dtype=np.int64)
    for i in range(1, 8):
        E[i, i, 0] = -1
    for (a, b, c), s in zip(FANO, signs):
        for x, y, z in ((a, b, c), (b, c, a), (c, a, b)):
            E[x, y, z] = s
            E[y, x, z] = -s
    return E


def left_mults(E):
    """L_a[j, k] = coefficient of e_k in e_a * e_j.  Integer."""
    return [np.array([[E[a, j, k] for j in range(8)] for k in range(8)],
                     dtype=np.int64) for a in range(1, 8)]


def clifford_exact(Ls):
    """{L_a, L_b} = -2 delta_ab I, checked in integers."""
    I8 = np.eye(8, dtype=np.int64)
    for a in range(7):
        for b in range(7):
            anti = Ls[a] @ Ls[b] + Ls[b] @ Ls[a]
            target = -2 * I8 if a == b else np.zeros((8, 8), dtype=np.int64)
            if not np.array_equal(anti, target):
                return False
    return True


def norm_sampled(E, trials=6, seed=0):
    """The weaker criterion, for comparison only."""
    rng = np.random.default_rng(seed)
    Ef = E.astype(float)
    for _ in range(trials):
        x, y = rng.normal(size=8), rng.normal(size=8)
        p = np.einsum('ijk,i,j->k', Ef, x, y)
        if abs(np.linalg.norm(p)
               - np.linalg.norm(x) * np.linalg.norm(y)) > 1e-9:
            return False
    return True


def main():
    print("=" * 70)
    print("D8 :: THEOREM 5.1 IN EXACT ARITHMETIC")
    print("=" * 70)

    exact, sampled = set(), set()
    for mask in range(128):
        signs = [1 if (mask >> b) & 1 == 0 else -1 for b in range(7)]
        E = table_int(signs)
        if clifford_exact(left_mults(E)):
            exact.add(mask)
        if norm_sampled(E):
            sampled.add(mask)

    print(f"\nX1  exact (integer Clifford relations) : {len(exact)} of 128"
          f"   [predicted 16 -> {'PASS' if len(exact) == 16 else 'MISS'}]")
    print(f"    orientations: {sorted(exact)}")
    print(f"\nX2  sampled (norm multiplicativity)    : {len(sampled)} of 128")
    print(f"    sets identical : "
          f"{'PASS' if exact == sampled else 'MISS'}")
    print("    -> the sampled criterion was correct, just weaker than a proof")

    # ---- X3/X4 the partition claim ----------------------------------
    print("\nX3  PARTITION OF THE 21 BIVECTORS BY THE SEVEN LINES")
    print("-" * 70)
    mask0 = sorted(exact)[0]
    signs = [1 if (mask0 >> b) & 1 == 0 else -1 for b in range(7)]
    Ls = left_mults(table_int(signs))
    pairs = [(a, b) for a in range(7) for b in range(a + 1, 7)]
    print(f"    unordered pairs of imaginary units : {len(pairs)}")
    line_of = {}
    for li, (a, b, c) in enumerate(FANO):
        for p in ((a - 1, b - 1), (b - 1, c - 1), (a - 1, c - 1)):
            line_of[tuple(sorted(p))] = li
    counts = [sum(1 for p in pairs if line_of[p] == li) for li in range(7)]
    print(f"    pairs per line : {counts}"
          f"   [predicted all 3 -> "
          f"{'PASS' if counts == [3] * 7 else 'MISS'}]")
    print(f"    every pair assigned exactly once : "
          f"{'PASS' if len(line_of) == 21 else 'MISS'}")
    print("    -> this is the Steiner property restated, not a new fact")

    blocks = []
    for li in range(7):
        vs = [(Ls[a] @ Ls[b]).astype(float).ravel()
              for (a, b) in pairs if line_of[(a, b)] == li]
        blocks.append(np.array(vs))
    dims = [np.linalg.matrix_rank(B, tol=1e-8) for B in blocks]
    allv = np.vstack(blocks)
    total = np.linalg.matrix_rank(allv, tol=1e-8)
    cross = 0.0
    for i in range(7):
        for j in range(i + 1, 7):
            cross = max(cross, np.max(np.abs(blocks[i] @ blocks[j].T)))
    print(f"\nX4  block dimensions : {dims}   total rank {total}"
          f"   [predicted 3x7 = 21 -> "
          f"{'PASS' if dims == [3] * 7 and total == 21 else 'MISS'}]")
    print(f"    max cross-block trace-form overlap : {cross:.3e}"
          f"   [{'PASS' if cross < 1e-8 else 'MISS'}]")
    print("    -> blocks are mutually orthogonal; 'partitioned' is literal")

    print("\n" + "=" * 70)
    print("READING")
    print("=" * 70)
    print("  Theorem 5.1's count is correct and can be established EXACTLY,")
    print("  with no sampling and no tolerance. The document should cite the")
    print("  Clifford criterion it already mentions rather than offering")
    print("  random-vector residuals as an alternative justification.")
    print()
    print("  The partition claim is true and follows in one line from the")
    print("  Steiner property. Stating it alongside the 21-dimensionality as")
    print("  though both were enumeration outputs understates it.")


if __name__ == "__main__":
    main()
