#!/usr/bin/env python3
"""
sigma_topology.py — opening the base thread: what can live on the cone?

The algebraic thread finished with a fully specified sigma model: base = the
D2 cone, target = the orbit of octonion structures, metric forced up to one
scale, no WZ term, no potential. This opens the base side.

Two facts about 2-dimensional sigma models decide most of what is possible
before any dynamics is solved:

  (i) harmonic maps from a surface are CONFORMALLY INVARIANT, and a cone is
      flat away from its apex. So the deficit angle zeta cannot enter the
      local field equations at all -- it can only enter through the global
      periodicity condition, i.e. through which windings close.

  (ii) topological sectors of maps from a surface are classified by pi_2 of
       the target, and finite-energy solitons by pi_1. So the target's
       homotopy decides whether solitons and winding sectors exist.

The target is the orbit of the octonion structure under the holonomy group.
z1_hinge.py's holonomy is generated by commutators of LEFT-MULTIPLICATION
operators on the full 8-dimensional O -- the spinor representation. That makes
the group Spin(7), not SO(7), and the orbit Spin(7)/G2 rather than SO(7)/G2.
The two differ exactly in their topology: S^7 versus RP^7.

This distinguishes them by computation rather than assertion: if the group is
Spin(7) acting on the spinor rep, its orbit through the unit octonion 1 is the
FULL unit sphere S^7 in O -- transitive, 7-dimensional, spanning all 8
coordinates. If it were the vector representation the orbit would sit inside a
7-dimensional subspace.

PREDICTIONS STATED BEFORE RUNNING
 S1 the holonomy algebra is 21-dimensional and acts on R^8 (reproduces
    z1_hinge and z1_d8_attempt).
 S2 exp(X).1 has unit norm for every X in the algebra -- the orbit lies in the
    unit sphere of O.
 S3 the reachable set SPANS all 8 coordinates of O, so the orbit is the full
    S^7 and not a subsphere. Hence the group is Spin(7) and the target is
    Spin(7)/G2 = S^7.
 S4 the stabiliser of 1 has dimension 14 (= G2), so orbit dim = 21 - 14 = 7,
    matching dim S^7.

 CONSEQUENCES, which follow from S3 and need no further computation:
   pi_1(S^7) = 0  -> no winding sectors; the cone's deficit angle imposes NO
                     topological selection, whatever zeta is.
   pi_2(S^7) = 0  -> no topological solitons. A 2D sigma model normally gets
                     its instantons from pi_2 of the target (CP^n has pi_2 = Z);
                     this target has none.

Python 3 + NumPy only.

(Cone deficit renamed beta -> zeta on 2026-09-25, to free beta for the lattice
gyroscopic coupling; the code variable keeps the name beta/BETA.)
"""

import numpy as np
from itertools import permutations

TOL = 1e-9


def oriented_lines():
    LINES = [tuple(sorted(((i + s - 1) % 7) + 1 for s in (0, 1, 3)))
             for i in range(1, 8)]
    used = {p: set() for p in range(1, 8)}
    assign = {}

    def bt(li):
        if li == len(LINES):
            return True
        Ln = LINES[li]
        for perm in permutations(range(3)):
            if all(perm[j] not in used[Ln[j]] for j in range(3)):
                for j in range(3):
                    used[Ln[j]].add(perm[j])
                assign[Ln] = perm
                if bt(li + 1):
                    return True
                for j in range(3):
                    used[Ln[j]].discard(perm[j])
                del assign[Ln]
        return False

    bt(0)
    return [tuple(Ln[assign[Ln].index(r)] for r in (0, 1, 2)) for Ln in LINES]


def octonion_table(oriented):
    E = np.zeros((8, 8, 8))
    E[0, :, :] = np.eye(8)
    E[:, 0, :] = np.eye(8)
    for i in range(1, 8):
        E[i, i, 0] = -1
    for (a, b, c) in oriented:
        for x, y, z in ((a, b, c), (b, c, a), (c, a, b)):
            E[x, y, z] = 1
            E[y, x, z] = -1
    return E


def expm(X, terms=60):
    n = max(0, int(np.ceil(np.log2(max(np.linalg.norm(X), 1e-12)))) + 2)
    A = X / (2.0 ** n)
    R = np.eye(X.shape[0])
    T = np.eye(X.shape[0])
    for k in range(1, terms):
        T = T @ A / k
        R = R + T
    for _ in range(n):
        R = R @ R
    return R


def main():
    oriented = oriented_lines()
    E = octonion_table(oriented)
    I8 = np.eye(8)
    print("=" * 70)
    print("SIGMA TOPOLOGY :: WHAT CAN LIVE ON THE CONE")
    print("=" * 70)

    # ---- S1 the holonomy algebra ------------------------------------
    Ls = [np.column_stack([np.einsum('ijk,i,j->k', E, I8[i], I8[j])
                           for j in range(8)]) for i in range(1, 8)]
    basis, flat = [], []
    for i in range(7):
        for j in range(i + 1, 7):
            M = Ls[i] @ Ls[j] - Ls[j] @ Ls[i]
            v = M.ravel()
            for b0 in flat:
                v = v - (v @ b0) * b0
            if np.linalg.norm(v) > 1e-8:
                flat.append(v / np.linalg.norm(v))
                basis.append((v / np.linalg.norm(v)).reshape(8, 8))
    print(f"\nS1  holonomy algebra dim = {len(basis)}   [predicted 21 -> "
          f"{'PASS' if len(basis) == 21 else 'MISS'}]")
    anti = max(np.linalg.norm(B + B.T) for B in basis)
    print(f"    all generators antisymmetric on R^8 : {anti:.2e}")

    # ---- S2/S3 the orbit through 1 ----------------------------------
    rng = np.random.default_rng(11)
    pts, norms = [], []
    for _ in range(400):
        X = sum(rng.normal() * B for B in basis)
        p = expm(X) @ I8[0]
        pts.append(p)
        norms.append(np.linalg.norm(p))
    norms = np.array(norms)
    print(f"\nS2  || exp(X).1 || : min {norms.min():.12f}, max {norms.max():.12f}"
          f"   [predicted 1 -> "
          f"{'PASS' if abs(norms - 1).max() < 1e-9 else 'MISS'}]")

    P = np.array(pts)
    rank = np.linalg.matrix_rank(P, tol=1e-8)
    print(f"\nS3  rank of reachable points in O = {rank}"
          f"   [predicted 8 -> {'PASS' if rank == 8 else 'MISS'}]")
    print("    -> the orbit is the FULL unit sphere S^7, not a subsphere")
    print("    -> the group is Spin(7) on the spinor rep; target = Spin(7)/G2")

    # ---- S4 stabiliser of 1 -----------------------------------------
    rows = np.array([(B @ I8[0]) for B in basis])       # 21 x 8
    stab = 21 - np.linalg.matrix_rank(rows, tol=1e-8)
    print(f"\nS4  dim stabiliser of 1 = {stab}   [predicted 14 = G2 -> "
          f"{'PASS' if stab == 14 else 'MISS'}]")
    print(f"    orbit dimension = 21 - {stab} = {21 - stab}   [dim S^7 = 7]")

    print("\n" + "=" * 70)
    print("CONSEQUENCES")
    print("=" * 70)
    print("  target = S^7 :  pi_1 = 0  and  pi_2 = 0.")
    print()
    print("  pi_2 = 0  -> NO topological solitons. A 2D sigma model normally")
    print("              takes its instantons from pi_2 of the target; this")
    print("              one has none. Nothing to count, nothing to quantise.")
    print("  pi_1 = 0  -> NO winding sectors. The cone's deficit angle zeta")
    print("              cannot select among topological classes because there")
    print("              are none to select among.")
    print()
    print("  Combined with conformal invariance in 2D and a cone being flat")
    print("  away from its apex, zeta drops out of the local field equations")
    print("  as well. On present structure the deficit angle does not couple")
    print("  to the octonion-structure field at all.")


if __name__ == "__main__":
    main()
