#!/usr/bin/env python3
"""
z1_d8_minimality.py — can the top rung be reached parameter-free?

The previous session left one unforced thing at D8: a sign. Minimality removes
the second generator b (G2 acts transitively on unit imaginary octonions, so a
normalises away, but an independent b carries a residual SU(3) orbit), leaving
exactly two parameter-free laws:

    anticommutator   psi-dot = psi a + a psi
    commutator       psi-dot = psi a - a psi

Conservativity, persistence and plurality are all silent on the sign. This asks
what the two laws actually ARE, rather than which is preferred.

ALGEBRA FIRST. For imaginary a and psi = psi_0 + psi_vec:

    psi a + a psi = 2 psi_0 a - 2 <psi_vec, a>      -- lies in span{1, a}
    psi a - a psi = 2 psi_vec x a                   -- purely imaginary

If those hold, the anticommutator rotates a single COMPLEX line and freezes
everything else, while the commutator rotates the imaginary part about a and
generates a QUATERNION copy. Neither would be a D8 flow: one is the D2 rung
re-embedded, the other the D4 rung re-embedded. The genuinely octonionic flow
was the generic two-generator one -- sweep 5, associator nonzero, 14 terms --
and it needs the b that minimality forbids.

That would put MINIMALITY AND D8 CONTENT IN DIRECT TENSION: eliminating the
free parameter drops you to a lower rung, and reaching the top rung costs a
parameter nothing forces.

PREDICTIONS STATED BEFORE RUNNING
 M1 the anticommutator velocity lies in span{1, a} to machine precision, for
    random psi and a.
 M2 under the anticommutator flow, the components of psi_vec orthogonal to a
    are CONSTANT in time.
 M3 the commutator velocity is purely imaginary and equals 2 psi_vec x a.
 M4 the algebra generated by the commutator trajectory is 4-dimensional and
    associative -- a quaternion copy, i.e. D4.
 M5 the algebra generated by the anticommutator trajectory is 2-dimensional
    and commutative -- a complex line, i.e. D2.
    [MISSED: dim 4 for both. The prediction conflated the SPAN OF THE MOTION
    with the ALGEBRA that span closes into. The anticommutator carries psi_0's
    frozen perpendicular component along without moving it, so the trajectory
    spans {1, a, psi_perp} and closes to a quaternion copy — while the MOTION
    only ever explores the (1, a) plane. The measurement that matters is the
    imaginary support of the motion: 2, below the three indices phi requires,
    hence zero terms.]
 M6 therefore neither parameter-free law is a D8 flow, and D8 content requires
    the unforced second generator.

Python 3 + NumPy only.
"""

import numpy as np
import importlib.util
import os

_here = os.path.dirname(os.path.abspath(__file__))
spec = importlib.util.spec_from_file_location(
    "fl", os.path.join(_here, "z1_d8_flow.py"))
fl = importlib.util.module_from_spec(spec)
spec.loader.exec_module(fl)
ch = fl.ch


def cross_im(u, v, c):
    return np.einsum('abe,a,b->e', c, u, v)


def main():
    orient = ch.oriented_lines()
    E = fl.oct_table(orient)
    c = ch.imaginary_c(orient)
    rng = np.random.default_rng(617)
    print("=" * 70)
    print("CAN THE TOP RUNG BE REACHED PARAMETER-FREE?")
    print("=" * 70)

    # ---- M1/M3 the two velocity fields ------------------------------
    print("\nM1/M3  WHAT THE TWO PARAMETER-FREE LAWS COMPUTE")
    print("-" * 70)
    w_anti, w_comm = 0.0, 0.0
    for _ in range(400):
        psi = rng.normal(size=8)
        psi /= np.linalg.norm(psi)
        a = np.zeros(8)
        a[1:] = rng.normal(size=7)
        a[1:] /= np.linalg.norm(a[1:])
        anti = fl.mul(psi, a, E) + fl.mul(a, psi, E)
        comm = fl.mul(psi, a, E) - fl.mul(a, psi, E)
        # closed form: anticommutator = 2 psi_0 a - 2 <psi_vec, a>
        pred_a = 2.0 * psi[0] * a
        pred_a[0] = -2.0 * (psi[1:] @ a[1:])
        # closed form: commutator = 2 psi_vec x a
        pred_c = np.zeros(8)
        pred_c[1:] = 2.0 * cross_im(psi[1:], a[1:], c)
        w_anti = max(w_anti, np.max(np.abs(anti - pred_a)))
        w_comm = max(w_comm, np.max(np.abs(comm - pred_c)))
    print(f"    | (psi a + a psi) - (2 psi_0 a - 2<psi_vec,a>) | = {w_anti:.3e}"
          f"   [{'PASS' if w_anti < 1e-12 else 'MISS'}]")
    print(f"    | (psi a - a psi) - 2 psi_vec x a |             = {w_comm:.3e}"
          f"   [{'PASS' if w_comm < 1e-12 else 'MISS'}]")

    # ---- M2 what the anticommutator freezes -------------------------
    print("\nM2  WHAT THE ANTICOMMUTATOR LEAVES FIXED")
    print("-" * 70)
    psi0 = rng.normal(size=8)
    psi0 /= np.linalg.norm(psi0)
    a = np.zeros(8)
    a[1:] = rng.normal(size=7)
    a[1:] /= np.linalg.norm(a[1:])
    tr_a = fl.integrate(psi0, lambda p: fl.mul(p, a, E) + fl.mul(a, p, E))
    perp = tr_a[:, 1:] - np.outer(tr_a[:, 1:] @ a[1:], a[1:])
    drift = np.max(np.abs(perp - perp[0]))
    print(f"    max drift of psi_vec orthogonal to a : {drift:.3e}"
          f"   [predict 0 -> {'PASS' if drift < 1e-9 else 'MISS'}]")
    print("    -> the anticommutator rotates the (1, a) plane and freezes"
          " the rest")

    # ---- M4/M5 the algebras generated -------------------------------
    print("\nM4/M5  THE ALGEBRA EACH TRAJECTORY GENERATES")
    print("-" * 70)
    tr_c = fl.integrate(psi0, lambda p: fl.mul(p, a, E) - fl.mul(a, p, E))

    def generated(traj):
        """Close the trajectory's span under octonion multiplication."""
        U, s, Vt = np.linalg.svd(traj, full_matrices=False)
        basis = [v for v, sv in zip(Vt, s) if sv > 1e-8 * s[0]]
        flat = []
        for v in basis:
            w = v.copy()
            for b in flat:
                w -= (w @ b) * b
            if np.linalg.norm(w) > 1e-8:
                flat.append(w / np.linalg.norm(w))
        for _ in range(6):
            grew = False
            for x in list(flat):
                for y in list(flat):
                    p = fl.mul(x, y, E)
                    for b in flat:
                        p -= (p @ b) * b
                    if np.linalg.norm(p) > 1e-8:
                        flat.append(p / np.linalg.norm(p))
                        grew = True
            if not grew:
                break
        return flat

    for name, tr in (("commutator    ", tr_c), ("anticommutator", tr_a)):
        alg = generated(tr)
        worst_a = 0.0
        worst_c = 0.0
        for _ in range(200):
            x, y, z = (sum(rng.normal() * b for b in alg) for _ in range(3))
            worst_a = max(worst_a, np.linalg.norm(
                fl.assoc(x, y, z, E)) / max(np.linalg.norm(x)
                                            * np.linalg.norm(y)
                                            * np.linalg.norm(z), 1e-30))
            worst_c = max(worst_c, np.linalg.norm(
                fl.mul(x, y, E) - fl.mul(y, x, E)))
        tag = ("D2 (complex)" if len(alg) == 2 else
               "D4 (quaternion)" if len(alg) == 4 else
               f"dim {len(alg)}")
        print(f"    {name} : generated algebra dim {len(alg)}  -> {tag}")
        print(f"                     associator {worst_a:.2e},  "
              f"commutator {worst_c:.2e}")

    print("\n" + "=" * 70)
    print("READING")
    print("=" * 70)
    print("  Neither parameter-free law is a D8 flow. Judged by the MOTION")
    print("  rather than the algebra its span closes into: the anticommutator")
    print("  has imaginary support 2 -- one complex line, everything else")
    print("  frozen -- and the commutator has support 3, a quaternion")
    print("  imaginary space with vanishing associator. D2 and D4 motion")
    print("  re-embedded at the top rung.")
    print()
    print("  So the sign was never a choice between two D8 theories. It is a")
    print("  choice of WHICH LOWER RUNG to re-run inside the top one.")
    print()
    print("  MINIMALITY AND D8 CONTENT ARE IN TENSION. Eliminating the second")
    print("  generator is what drops you to a lower rung; the only flow that")
    print("  reaches genuinely octonionic content is the generic two-generator")
    print("  one, and it carries a parameter nothing forces.")


if __name__ == "__main__":
    main()
